//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ringtoets.GrassCoverErosionInwards.IO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ringtoets.GrassCoverErosionInwards.IO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout bij het aanmaken van een dijk profiel locatie: Id is ongeldig..
        /// </summary>
        internal static string DikeProfileLocation_Constructor_Invalid_Id {
            get {
                return ResourceManager.GetString("DikeProfileLocation_Constructor_Invalid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout bij het aanmaken van een dijk profiel locatie: Naam is ongeldig..
        /// </summary>
        internal static string DikeProfileLocation_Constructor_Invalid_Name {
            get {
                return ResourceManager.GetString("DikeProfileLocation_Constructor_Invalid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout bij het aanmaken van een dijk profiel locatie: Punt is ongeldig..
        /// </summary>
        internal static string DikeProfileLocation_Constructor_Invalid_Point {
            get {
                return ResourceManager.GetString("DikeProfileLocation_Constructor_Invalid_Point", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout bij het aanmaken van een dijk profiel locatie: X0 is ongeldig..
        /// </summary>
        internal static string DikeProfileLocation_Constructor_Invalid_X0 {
            get {
                return ResourceManager.GetString("DikeProfileLocation_Constructor_Invalid_X0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bestand heeft een attribuut &apos;ID&apos; zonder geldige waarde, welke vereist is om de locaties van de dijkprofielen in te lezen..
        /// </summary>
        internal static string DikeProfileLocationReader_GetDikeProfileLocations_Invalid_Id {
            get {
                return ResourceManager.GetString("DikeProfileLocationReader_GetDikeProfileLocations_Invalid_Id", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bestand heeft een attribuut &apos;Naam&apos; zonder geldige waarde, welke vereist is om de locaties van de dijkprofielen in te lezen..
        /// </summary>
        internal static string DikeProfileLocationReader_GetDikeProfileLocations_Invalid_Name {
            get {
                return ResourceManager.GetString("DikeProfileLocationReader_GetDikeProfileLocations_Invalid_Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bestand heeft een attribuut &apos;X0&apos; zonder geldige waarde, welke vereist is om de locaties van de dijkprofielen in te lezen..
        /// </summary>
        internal static string DikeProfileLocationReader_GetDikeProfileLocations_Invalid_X0 {
            get {
                return ResourceManager.GetString("DikeProfileLocationReader_GetDikeProfileLocations_Invalid_X0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bestand mag uitsluitend punten bevatten..
        /// </summary>
        internal static string DikeProfileLocationReader_OpenPointsShapeFile_File_can_only_contain_points {
            get {
                return ResourceManager.GetString("DikeProfileLocationReader_OpenPointsShapeFile_File_can_only_contain_points", resourceCulture);
            }
        }
    }
}
