///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomatedSystemTests.Modules.Validation
{
    public partial class ValidateDetailedAssessmentTypeAtRow
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void ValidateDetailedAssessmentCell(RepoItemInfo cellInfo, string expectedValue)
        {
        	expectedValue = expectedValue.Replace(" ", String.Empty).Replace(".", String.Empty);
        	Report.Log(ReportLevel.Info, "Info", expectedValue, cellInfo);
        	Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleValue='" + expectedValue.ToString() + "') on item 'cellInfo'.", cellInfo);
        	string foundValue = cellInfo.CreateAdapter<Cell>(true).GetAttributeValue<String>("AccessibleValue");
        	foundValue = foundValue.Replace(" ", String.Empty).Replace(".", String.Empty);
            Validate.AreEqual(foundValue, expectedValue);
        }

    }
}
