///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomatedSystemTests.Modules.Selection
{
    public partial class SelectGenericSectionInListScenariosView
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void FocusSelectAndClick(RepoItemInfo listitemInfo)
        {
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Focus() on item 'listitemInfo'.", listitemInfo);
            listitemInfo.FindAdapter<ListItem>().Focus();
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'listitemInfo'.", listitemInfo);
            listitemInfo.FindAdapter<ListItem>().Select();
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'listitemInfo' at Center.", listitemInfo);
            listitemInfo.FindAdapter<ListItem>().Click();
        }

    }
}
