//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ringtoets.Piping.Service.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ringtoets.Piping.Service.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piping berekening niet gelukt: {0}.
        /// </summary>
        internal static string Error_in_piping_calculation_0 {
            get {
                return ResourceManager.GetString("Error_in_piping_calculation_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validatie mislukt: {0}.
        /// </summary>
        internal static string Error_in_piping_validation_0 {
            get {
                return ResourceManager.GetString("Error_in_piping_validation_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan het toetspeil niet afleiden op basis van de invoer..
        /// </summary>
        internal static string PipingCalculationService_ValidateInput_Cannot_determine_AssessmentLevel {
            get {
                return ResourceManager.GetString("PipingCalculationService_ValidateInput_Cannot_determine_AssessmentLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan de stijghoogte bij het uittredepunt niet afleiden op basis van de invoer..
        /// </summary>
        internal static string PipingCalculationService_ValidateInput_Cannot_determine_PiezometricHeadExit {
            get {
                return ResourceManager.GetString("PipingCalculationService_ValidateInput_Cannot_determine_PiezometricHeadExit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan de dikte van het watervoerend pakket niet afleiden op basis van de invoer..
        /// </summary>
        internal static string PipingCalculationService_ValidateInput_Cannot_determine_thickness_aquifer_layer {
            get {
                return ResourceManager.GetString("PipingCalculationService_ValidateInput_Cannot_determine_thickness_aquifer_layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kan de totale deklaagdikte bij het uittredepunt niet afleiden op basis van de invoer..
        /// </summary>
        internal static string PipingCalculationService_ValidateInput_Cannot_determine_thickness_coverage_layer {
            get {
                return ResourceManager.GetString("PipingCalculationService_ValidateInput_Cannot_determine_thickness_coverage_layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het uittredepunt ligt niet voorbij het intredepunt..
        /// </summary>
        internal static string PipingCalculationService_ValidateInput_EntryPointL_greater_or_equal_to_ExitPointL {
            get {
                return ResourceManager.GetString("PipingCalculationService_ValidateInput_EntryPointL_greater_or_equal_to_ExitPointL" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is geen hydraulische randvoorwaardenlocatie geselecteerd..
        /// </summary>
        internal static string PipingCalculationService_ValidateInput_No_HydraulicBoundaryLocation_selected {
            get {
                return ResourceManager.GetString("PipingCalculationService_ValidateInput_No_HydraulicBoundaryLocation_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is geen ondergrondschematisatie geselecteerd..
        /// </summary>
        internal static string PipingCalculationService_ValidateInput_No_StochasticSoilProfile_selected {
            get {
                return ResourceManager.GetString("PipingCalculationService_ValidateInput_No_StochasticSoilProfile_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is geen profielschematisatie geselecteerd..
        /// </summary>
        internal static string PipingCalculationService_ValidateInput_No_SurfaceLine_selected {
            get {
                return ResourceManager.GetString("PipingCalculationService_ValidateInput_No_SurfaceLine_selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is geen waarde voor het intredepunt opgegeven..
        /// </summary>
        internal static string PipingCalculationService_ValidateInput_No_value_for_EntryPointL {
            get {
                return ResourceManager.GetString("PipingCalculationService_ValidateInput_No_value_for_EntryPointL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is geen waarde voor het uittredepunt opgegeven..
        /// </summary>
        internal static string PipingCalculationService_ValidateInput_No_value_for_ExitPointL {
            get {
                return ResourceManager.GetString("PipingCalculationService_ValidateInput_No_value_for_ExitPointL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiligheidsfactor voor piping kan niet worden berekend..
        /// </summary>
        internal static string PipingSemiProbabilisticCalculationService_ValidateOutputOnCalculation_Factor_of_safety_cannot_be_calculated {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticCalculationService_ValidateOutputOnCalculation_Factor_of_s" +
                        "afety_cannot_be_calculated", resourceCulture);
            }
        }
    }
}
