///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutomatedSystemTests
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The SelectTrajectType recording.
    /// </summary>
    [TestModule("f3cd18f8-b687-4886-b040-fc89f784d832", ModuleType.Recording, 1)]
    public partial class SelectTrajectType : ITestModule
    {
        /// <summary>
        /// Holds an instance of the AutomatedSystemTestsRepository repository.
        /// </summary>
        public static AutomatedSystemTestsRepository repo = AutomatedSystemTestsRepository.Instance;

        static SelectTrajectType instance = new SelectTrajectType();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public SelectTrajectType()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static SelectTrajectType Instance
        {
            get { return instance; }
        }

#region Variables

        /// <summary>
        /// Gets or sets the value of variable substringTrajectName.
        /// </summary>
        [TestVariable("77ae6c27-603e-4704-add9-e1249169f0e5")]
        public string substringTrajectName
        {
            get { return repo.substringTrajectName; }
            set { repo.substringTrajectName = value; }
        }

        /// <summary>
        /// Gets or sets the value of variable trajectType.
        /// </summary>
        [TestVariable("7e8f3140-795e-40f1-a611-9c126ff7de4f")]
        public string trajectType
        {
            get { return repo.trajectType; }
            set { repo.trajectType = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Invoke action", "Invoking Select() on item 'RiskeerMainWindow.ProjectExplorer.ProjectRootNode.TrajectWithSubstringInName.Faalkansbegroting'.", repo.RiskeerMainWindow.ProjectExplorer.ProjectRootNode.TrajectWithSubstringInName.FaalkansbegrotingInfo, new RecordItemIndex(0));
            repo.RiskeerMainWindow.ProjectExplorer.ProjectRootNode.TrajectWithSubstringInName.Faalkansbegroting.Select();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RiskeerMainWindow.PropertiesPanelContainer.Table.Trajecttype' at CenterLeft.", repo.RiskeerMainWindow.PropertiesPanelContainer.Table.TrajecttypeInfo, new RecordItemIndex(1));
            repo.RiskeerMainWindow.PropertiesPanelContainer.Table.Trajecttype.Click(Location.CenterLeft);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'RiskeerMainWindow.PropertiesPanelContainer.Table.Trajecttype' at .98;.5.", repo.RiskeerMainWindow.PropertiesPanelContainer.Table.TrajecttypeInfo, new RecordItemIndex(2));
            repo.RiskeerMainWindow.PropertiesPanelContainer.Table.Trajecttype.Click(".98;.5");
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Riskeer.TrajectType' at Center.", repo.Riskeer.TrajectTypeInfo, new RecordItemIndex(3));
            repo.Riskeer.TrajectType.Click();
            
            Click_ButtonOK_If_Shown(repo.Bevestigen.ButtonOKInfo);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
