///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomatedSystemTests
{
    public partial class SetRangeInTableForPEBasedOnTrajectType
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public void SetRangeTablePEBasedInTrajectType()
        {
            string rangeTable = "";
            if (trajectType=="Dijk") {
            	rangeTable = "1-18";
            } else if (trajectType=="Duin") {
            	rangeTable = "19-36";
            } else if (trajectType=="Dijk / Duin") {
            	rangeTable = "37-54";
            }
            TestSuite.Current.GetTestContainer("ValidateContributionsOfAllFMsInProjectExplorer").DataContext.SetRange(DataRangeSet.Parse(rangeTable));
            Report.Log(ReportLevel.Info, "Range of next loop: " + rangeTable);
        }

    }
}
