// Copyright (C) Stichting Deltares 2019. All rights reserved.
//
// This file is part of Riskeer.
//
// Riskeer is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//
// All names, logos, and references to "Deltares" are registered trademarks of
// Stichting Deltares and remain full property of Stichting Deltares at all times.
// All rights reserved.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Common.Util.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Common.Util.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toegankelijk gebied moet geheel binnen de afbeelding vallen..
        /// </summary>
        public static string ColorAccess_Create_Accessible_area_outside_image_bounds_error {
            get {
                return ResourceManager.GetString("ColorAccess_Create_Accessible_area_outside_image_bounds_error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slechts de volgende waardes worden geaccepteerd: {0}..
        /// </summary>
        public static string ConvertFrom_Only_following_values_are_accepted_ParameterValues_0_ {
            get {
                return ResourceManager.GetString("ConvertFrom_Only_following_values_are_accepted_ParameterValues_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bestandspad verwijst naar een map die niet bestaat..
        /// </summary>
        public static string Error_Directory_missing {
            get {
                return ResourceManager.GetString("Error_Directory_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bestand bestaat niet..
        /// </summary>
        public static string Error_File_does_not_exist {
            get {
                return ResourceManager.GetString("Error_File_does_not_exist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bestand is leeg..
        /// </summary>
        public static string Error_File_empty {
            get {
                return ResourceManager.GetString("Error_File_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een onverwachte fout opgetreden tijdens het inlezen van het bestand &apos;{0}&apos;..
        /// </summary>
        public static string Error_General_IO_ErrorMessage_0_ {
            get {
                return ResourceManager.GetString("Error_General_IO_ErrorMessage_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bestand kon niet worden geopend. Mogelijk is het bestand corrupt of in gebruik door een andere applicatie..
        /// </summary>
        public static string Error_General_IO_Import_ErrorMessage {
            get {
                return ResourceManager.GetString("Error_General_IO_Import_ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een onverwachte fout opgetreden tijdens het schrijven van het bestand &apos;{0}&apos;..
        /// </summary>
        public static string Error_General_output_error_0 {
            get {
                return ResourceManager.GetString("Error_General_output_error_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Regel bevat te veel tekst om in het RAM geheugen opgeslagen te worden..
        /// </summary>
        public static string Error_Line_too_big_for_RAM {
            get {
                return ResourceManager.GetString("Error_Line_too_big_for_RAM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zitten ongeldige tekens in het bestandspad. Alle tekens in het bestandspad moeten geldig zijn..
        /// </summary>
        public static string Error_Path_cannot_contain_invalid_characters {
            get {
                return ResourceManager.GetString("Error_Path_cannot_contain_invalid_characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestandspad mag niet leeg of ongedefinieerd zijn..
        /// </summary>
        public static string Error_Path_must_be_specified {
            get {
                return ResourceManager.GetString("Error_Path_must_be_specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestandspad mag niet verwijzen naar een lege bestandsnaam..
        /// </summary>
        public static string Error_Path_must_not_point_to_empty_file_name {
            get {
                return ResourceManager.GetString("Error_Path_must_not_point_to_empty_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout bij het schrijven naar bestandsmap &apos;{0}&apos;: {1}.
        /// </summary>
        public static string Error_Writing_to_Directory_0_CustomMessage_1_ {
            get {
                return ResourceManager.GetString("Error_Writing_to_Directory_0_CustomMessage_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout bij het schrijven naar bestand &apos;{0}&apos;: {1}.
        /// </summary>
        public static string Error_Writing_to_File_0_CustomMessage_1_ {
            get {
                return ResourceManager.GetString("Error_Writing_to_File_0_CustomMessage_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alle bestanden.
        /// </summary>
        public static string FileFilterGenerator_All_Files {
            get {
                return ResourceManager.GetString("FileFilterGenerator_All_Files", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} (*.{1})|*.{1}.
        /// </summary>
        public static string FileFilterGenerator_File_filter_format {
            get {
                return ResourceManager.GetString("FileFilterGenerator_File_filter_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-bestanden.
        /// </summary>
        public static string FileFilterGenerator_Files_of_type_0_ {
            get {
                return ResourceManager.GetString("FileFilterGenerator_Files_of_type_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fout bij het lezen van bestand &apos;{0}&apos;{1}{2}: {3}.
        /// </summary>
        public static string FileReaderErrorMessageBuilder_Build_Error_while_reading_file_0_location_1_subject_2_errorMessage_3 {
            get {
                return ResourceManager.GetString("FileReaderErrorMessageBuilder_Build_Error_while_reading_file_0_location_1_subject" +
                        "_2_errorMessage_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is een fout opgetreden bij het verwijderen van bestanden in de map &apos;{0}&apos;..
        /// </summary>
        public static string IOUtils_DeleteOldFiles_Error_occurred_deleting_files_in_folder_0 {
            get {
                return ResourceManager.GetString("IOUtils_DeleteOldFiles_Error_occurred_deleting_files_in_folder_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen toegangsrechten tot bestandspad..
        /// </summary>
        public static string IOUtils_No_access_rights_to_path {
            get {
                return ResourceManager.GetString("IOUtils_No_access_rights_to_path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bestandspad moet opgegeven zijn..
        /// </summary>
        public static string IOUtils_Path_cannot_be_empty {
            get {
                return ResourceManager.GetString("IOUtils_Path_cannot_be_empty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bestandspad bevat een &apos;:&apos; op een ongeldige plek..
        /// </summary>
        public static string IOUtils_Path_contains_invalid_character {
            get {
                return ResourceManager.GetString("IOUtils_Path_contains_invalid_character", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het bestandspad is te lang..
        /// </summary>
        public static string IOUtils_Path_too_long {
            get {
                return ResourceManager.GetString("IOUtils_Path_too_long", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to op regel {0}.
        /// </summary>
        public static string TextFile_On_LineNumber_0_ {
            get {
                return ResourceManager.GetString("TextFile_On_LineNumber_0_", resourceCulture);
            }
        }
    }
}
