///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutomatedSystemTests.Modules.Validation.PropertiesPanel
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ValidateSurfaceLineNameInPropertiesPanel recording.
    /// </summary>
    [TestModule("200d05d0-2615-44bf-991e-2913171cd220", ModuleType.Recording, 1)]
    public partial class ValidateSurfaceLineNameInPropertiesPanel : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AutomatedSystemTests.AutomatedSystemTestsRepository repository.
        /// </summary>
        public static global::AutomatedSystemTests.AutomatedSystemTestsRepository repo = global::AutomatedSystemTests.AutomatedSystemTestsRepository.Instance;

        static ValidateSurfaceLineNameInPropertiesPanel instance = new ValidateSurfaceLineNameInPropertiesPanel();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ValidateSurfaceLineNameInPropertiesPanel()
        {
            expectedSurfaceLineName = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ValidateSurfaceLineNameInPropertiesPanel Instance
        {
            get { return instance; }
        }

#region Variables

        string _expectedSurfaceLineName;

        /// <summary>
        /// Gets or sets the value of variable expectedSurfaceLineName.
        /// </summary>
        [TestVariable("a8e3cb99-db08-4cce-a138-eb8382ed259c")]
        public string expectedSurfaceLineName
        {
            get { return _expectedSurfaceLineName; }
            set { _expectedSurfaceLineName = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Screenshot(ReportLevel.Info, "User", "", repo.RiskeerMainWindow.PropertiesPanelContainer.Table.Name, false, new RecordItemIndex(0));
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (AccessibleValue=$expectedSurfaceLineName) on item 'RiskeerMainWindow.PropertiesPanelContainer.Table.Name'.", repo.RiskeerMainWindow.PropertiesPanelContainer.Table.NameInfo, new RecordItemIndex(1));
            Validate.AttributeEqual(repo.RiskeerMainWindow.PropertiesPanelContainer.Table.NameInfo, "AccessibleValue", expectedSurfaceLineName);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
