<!--
Copyright (C) Stichting Deltares and State of the Netherlands 2026. All rights reserved.

This file is part of Riskeer.

Riskeer is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program. If not, see <https://www.gnu.org/licenses/>.

All names, logos, and references to "Deltares" are registered trademarks of
Stichting Deltares and remain full property of Stichting Deltares at all times.
All rights reserved.
-->
<Project Sdk="Microsoft.NET.Sdk">
  <Import Project="$(SolutionDir)build\Test.targets" />
  <ItemGroup>
    <Reference Include="System" />
    <Reference Include="System.Core" />
    <Reference Include="System.Drawing" />
  </ItemGroup>
  <ItemGroup>
    <None Include="..\..\..\..\build\Copying.Lesser.licenseheader">
      <Link>Copying.Lesser.licenseheader</Link>
    </None>
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\src\Core.Common.Base\Core.Common.Base.csproj"/>
    <ProjectReference Include="..\..\..\Common\test\Core.Common.TestUtil\Core.Common.TestUtil.csproj"/>
    <ProjectReference Include="..\..\src\Core.Components.Chart\Core.Components.Chart.csproj"/>
    <ProjectReference Include="..\..\src\Core.Components.OxyPlot\Core.Components.OxyPlot.csproj"/>
    <ProjectReference Include="..\..\src\Core.Components.Stack\Core.Components.Stack.csproj"/>
    <ProjectReference Include="..\Core.Components.Chart.TestUtil\Core.Components.Chart.TestUtil.csproj"/>
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="NSubstitute">
      <Version>4.4.0</Version>
    </PackageReference>
    <PackageReference Include="NUnit">
      <Version>3.8.1</Version>
    </PackageReference>
    <PackageReference Include="OxyPlot.Core">
      <Version>1.0.0</Version>
    </PackageReference>
  </ItemGroup>
</Project>
