// Copyright (C) Stichting Deltares 2016. All rights reserved.
//
// This file is part of Ringtoets.
//
// Ringtoets is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//
// All names, logos, and references to "Deltares" are registered trademarks of
// Stichting Deltares and remain full property of Stichting Deltares at all times.
// All rights reserved.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ringtoets.Piping.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ringtoets.Piping.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karakteristieke punten.
        /// </summary>
        public static string Categories_Characteristic_points {
            get {
                return ResourceManager.GetString("Categories_Characteristic_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heave.
        /// </summary>
        public static string Categories_Heave {
            get {
                return ResourceManager.GetString("Categories_Heave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terugschrijdende erosie (Sellmeijer).
        /// </summary>
        public static string Categories_Sellmeijer {
            get {
                return ResourceManager.GetString("Categories_Sellmeijer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Semi-probabilistische parameters.
        /// </summary>
        public static string Categories_SemiProbabilisticParameters {
            get {
                return ResourceManager.GetString("Categories_SemiProbabilisticParameters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opbarsten.
        /// </summary>
        public static string Categories_Uplift {
            get {
                return ResourceManager.GetString("Categories_Uplift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De representatieve waarde die gebruikt wordt door de berekening..
        /// </summary>
        public static string DesignVariableTypeConverter_DesignValue_Description {
            get {
                return ResourceManager.GetString("DesignVariableTypeConverter_DesignValue_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekenwaarde.
        /// </summary>
        public static string DesignVariableTypeConverter_DesignValue_DisplayName {
            get {
                return ResourceManager.GetString("DesignVariableTypeConverter_DesignValue_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type verdeling.
        /// </summary>
        public static string DesignVariableTypeConverter_DestributionType_DisplayName {
            get {
                return ResourceManager.GetString("DesignVariableTypeConverter_DestributionType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het soort kansverdeling waarin deze parameter gedefinieerd wordt..
        /// </summary>
        public static string DesignVariableTypeConverter_DistributionType_Description {
            get {
                return ResourceManager.GetString("DesignVariableTypeConverter_DistributionType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De parameter &apos;a&apos; die gebruikt wordt voor het lengte-effect in berekening van de maximaal toelaatbare faalkans..
        /// </summary>
        public static string GeneralPipingInput_A_Description {
            get {
                return ResourceManager.GetString("GeneralPipingInput_A_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to a [-].
        /// </summary>
        public static string GeneralPipingInput_A_DisplayName {
            get {
                return ResourceManager.GetString("GeneralPipingInput_A_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De parameter &apos;b&apos; die gebruikt wordt voor het lengte-effect in berekening van de maximaal toelaatbare faalkans..
        /// </summary>
        public static string GeneralPipingInput_B_Description {
            get {
                return ResourceManager.GetString("GeneralPipingInput_B_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to b [m].
        /// </summary>
        public static string GeneralPipingInput_B_DisplayName {
            get {
                return ResourceManager.GetString("GeneralPipingInput_B_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hoek in het krachtenevenwicht die aangeeft hoeveel weerstand de korrels bieden tegen rollen; ook beddingshoek genoemd..
        /// </summary>
        public static string GeneralPipingInput_BeddingAngle_Description {
            get {
                return ResourceManager.GetString("GeneralPipingInput_BeddingAngle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rolweerstandshoek [°].
        /// </summary>
        public static string GeneralPipingInput_BeddingAngle_DisplayName {
            get {
                return ResourceManager.GetString("GeneralPipingInput_BeddingAngle_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kritiek verhang met betrekking tot heave..
        /// </summary>
        public static string GeneralPipingInput_CriticalHeaveGradient_Description {
            get {
                return ResourceManager.GetString("GeneralPipingInput_CriticalHeaveGradient_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kritiek verhang m.b.t. heave [-].
        /// </summary>
        public static string GeneralPipingInput_CriticalHeaveGradient_DisplayName {
            get {
                return ResourceManager.GetString("GeneralPipingInput_CriticalHeaveGradient_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemiddelde d70 van de in kleine schaalproeven toegepaste zandsoorten, waarop de formule van Sellmeijer is gefit..
        /// </summary>
        public static string GeneralPipingInput_MeanDiameter70_Description {
            get {
                return ResourceManager.GetString("GeneralPipingInput_MeanDiameter70_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Referentiewaarde voor 70%-fraktiel in Sellmeijer regel [m].
        /// </summary>
        public static string GeneralPipingInput_MeanDiameter70_DisplayName {
            get {
                return ResourceManager.GetString("GeneralPipingInput_MeanDiameter70_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het (ondergedompelde) volumegewicht van zandkorrelmateriaal van een zandlaag..
        /// </summary>
        public static string GeneralPipingInput_SandParticlesVolumicWeight_Description {
            get {
                return ResourceManager.GetString("GeneralPipingInput_SandParticlesVolumicWeight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumiek gewicht van de zandkorrels onder water [kN/m³].
        /// </summary>
        public static string GeneralPipingInput_SandParticlesVolumicWeight_DisplayName {
            get {
                return ResourceManager.GetString("GeneralPipingInput_SandParticlesVolumicWeight_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekenwaarde om de onzekerheid in het model van Sellmeijer in rekening te brengen..
        /// </summary>
        public static string GeneralPipingInput_SellmeijerModelFactor_Description {
            get {
                return ResourceManager.GetString("GeneralPipingInput_SellmeijerModelFactor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelfactor piping toegepast op het model van Sellmeijer [-].
        /// </summary>
        public static string GeneralPipingInput_SellmeijerModelFactor_DisplayName {
            get {
                return ResourceManager.GetString("GeneralPipingInput_SellmeijerModelFactor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reductiefactor Sellmeijer..
        /// </summary>
        public static string GeneralPipingInput_SellmeijerReductionFactor_Description {
            get {
                return ResourceManager.GetString("GeneralPipingInput_SellmeijerReductionFactor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reductiefactor Sellmeijer [-].
        /// </summary>
        public static string GeneralPipingInput_SellmeijerReductionFactor_DisplayName {
            get {
                return ResourceManager.GetString("GeneralPipingInput_SellmeijerReductionFactor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De veiligheidsfactor die wordt vergeleken met de berekende stabiliteitsfactor van het submechanisme opbarsten..
        /// </summary>
        public static string GeneralPipingInput_UpliftCriticalSafetyFactor_Description {
            get {
                return ResourceManager.GetString("GeneralPipingInput_UpliftCriticalSafetyFactor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kritische veiligheidsfactor voor opbarsten [-].
        /// </summary>
        public static string GeneralPipingInput_UpliftCriticalSafetyFactor_DisplayName {
            get {
                return ResourceManager.GetString("GeneralPipingInput_UpliftCriticalSafetyFactor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekenwaarde om de onzekerheid in het model van opbarsten in rekening te brengen..
        /// </summary>
        public static string GeneralPipingInput_UpliftModelFactor_Description {
            get {
                return ResourceManager.GetString("GeneralPipingInput_UpliftModelFactor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelfactor opbarsten [-].
        /// </summary>
        public static string GeneralPipingInput_UpliftModelFactor_DisplayName {
            get {
                return ResourceManager.GetString("GeneralPipingInput_UpliftModelFactor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinematische viscositeit van water bij 10° C..
        /// </summary>
        public static string GeneralPipingInput_WaterKinematicViscosity_Description {
            get {
                return ResourceManager.GetString("GeneralPipingInput_WaterKinematicViscosity_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kinematische viscositeit van water bij 10° C [m²/s].
        /// </summary>
        public static string GeneralPipingInput_WaterKinematicViscosity_DisplayName {
            get {
                return ResourceManager.GetString("GeneralPipingInput_WaterKinematicViscosity_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumiek gewicht van water..
        /// </summary>
        public static string GeneralPipingInput_WaterVolumetricWeight_Description {
            get {
                return ResourceManager.GetString("GeneralPipingInput_WaterVolumetricWeight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Volumiek gewicht van water [kN/m³].
        /// </summary>
        public static string GeneralPipingInput_WaterVolumetricWeight_DisplayName {
            get {
                return ResourceManager.GetString("GeneralPipingInput_WaterVolumetricWeight_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sleepkrachtfactor volgens White..
        /// </summary>
        public static string GeneralPipingInput_WhitesDragCoefficient_Description {
            get {
                return ResourceManager.GetString("GeneralPipingInput_WhitesDragCoefficient_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coëfficiënt van White [-].
        /// </summary>
        public static string GeneralPipingInput_WhitesDragCoefficient_DisplayName {
            get {
                return ResourceManager.GetString("GeneralPipingInput_WhitesDragCoefficient_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap ImportIcon {
            get {
                object obj = ResourceManager.GetObject("ImportIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lognormale verdeling.
        /// </summary>
        public static string LogNormalDistribution_DisplayName {
            get {
                return ResourceManager.GetString("LogNormalDistribution_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lognormaal.
        /// </summary>
        public static string LogNormalDistribution_ShortName {
            get {
                return ResourceManager.GetString("LogNormalDistribution_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normale verdeling.
        /// </summary>
        public static string NormalDistribution_DisplayName {
            get {
                return ResourceManager.GetString("NormalDistribution_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normaal.
        /// </summary>
        public static string NormalDistribution_ShortName {
            get {
                return ResourceManager.GetString("NormalDistribution_ShortName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string PipingCalculation_Name_DisplayName {
            get {
                return ResourceManager.GetString("PipingCalculation_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen ondergrondschematisaties gevonden voor profielschematisatie &apos;{0}&apos;. De profielschematisatie is overgeslagen..
        /// </summary>
        public static string PipingCalculationConfigurationHelper_GenerateCalculationsStructure_No_PipingSoilProfile_found_for_RingtoetsPipingSurfaceLine_0_skipped {
            get {
                return ResourceManager.GetString("PipingCalculationConfigurationHelper_GenerateCalculationsStructure_No_PipingSoilP" +
                        "rofile_found_for_RingtoetsPipingSurfaceLine_0_skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn geen profielschematisaties of stochastische ondergrondmodellen beschikbaar om berekeningen voor te genereren..
        /// </summary>
        public static string PipingCalculationGroup_Generate_PipingCalculations_NoSurfaceLinesOrSoilModels_ToolTip {
            get {
                return ResourceManager.GetString("PipingCalculationGroup_Generate_PipingCalculations_NoSurfaceLinesOrSoilModels_Too" +
                        "lTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genereer scenario&apos;s op basis van geselecteerde profielschematisaties..
        /// </summary>
        public static string PipingCalculationGroup_Generate_PipingCalculations_ToolTip {
            get {
                return ResourceManager.GetString("PipingCalculationGroup_Generate_PipingCalculations_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bijdrage aan scenario [%].
        /// </summary>
        public static string PipingCalculationsView_InitializeDataGridView_Contribution {
            get {
                return ResourceManager.GetString("PipingCalculationsView_InitializeDataGridView_Contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In oordeel.
        /// </summary>
        public static string PipingCalculationsView_InitializeDataGridView_In_final_rating {
            get {
                return ResourceManager.GetString("PipingCalculationsView_InitializeDataGridView_In_final_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aandeel van schematisatie in het stochastische ondergrondmodel [%].
        /// </summary>
        public static string PipingCalculationsView_InitializeDataGridView_Stochastic_soil_profile_probability {
            get {
                return ResourceManager.GetString("PipingCalculationsView_InitializeDataGridView_Stochastic_soil_profile_probability" +
                        "", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dempingsfactor relateert respons van stijghoogte bij binnenteen aan buitenwaterstand..
        /// </summary>
        public static string PipingInput_DampingFactorExit_Description {
            get {
                return ResourceManager.GetString("PipingInput_DampingFactorExit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dempingsfactor bij uittredepunt [-].
        /// </summary>
        public static string PipingInput_DampingFactorExit_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_DampingFactorExit_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Darcy-snelheid waarmee water door de eerste voor doorlatendheid te onderscheiden zandlaag loopt..
        /// </summary>
        public static string PipingInput_DarcyPermeability_Description {
            get {
                return ResourceManager.GetString("PipingInput_DarcyPermeability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Doorlatendheid aquifer [m/s].
        /// </summary>
        public static string PipingInput_DarcyPermeability_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_DarcyPermeability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zeefmaat waar 70 gewichtsprocent van de korrels uit een zandlaag doorheen gaat. Hier de korreldiameter van het bovenste gedeelte van de voor doorlatendheid te onderscheiden zandlaag, bepaald zonder fijne fractie (&lt; 63µm)..
        /// </summary>
        public static string PipingInput_Diameter70_Description {
            get {
                return ResourceManager.GetString("PipingInput_Diameter70_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 70%-fraktiel van de korreldiameter in de bovenste zandlaag [m].
        /// </summary>
        public static string PipingInput_Diameter70_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_Diameter70_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De positie in het dwarsprofiel van het intredepunt..
        /// </summary>
        public static string PipingInput_EntryPointL_Description {
            get {
                return ResourceManager.GetString("PipingInput_EntryPointL_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intredepunt.
        /// </summary>
        public static string PipingInput_EntryPointL_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_EntryPointL_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De positie in het dwarsprofiel van het uittredepunt..
        /// </summary>
        public static string PipingInput_ExitPointL_Description {
            get {
                return ResourceManager.GetString("PipingInput_ExitPointL_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uittredepunt.
        /// </summary>
        public static string PipingInput_ExitPointL_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_ExitPointL_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De locatie met hydraulische randvoorwaarden waarvan het berekende toetspeil wordt gebruikt..
        /// </summary>
        public static string PipingInput_HydraulicBoundaryLocation_Description {
            get {
                return ResourceManager.GetString("PipingInput_HydraulicBoundaryLocation_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locatie met hydraulische randvoorwaarden.
        /// </summary>
        public static string PipingInput_HydraulicBoundaryLocation_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_HydraulicBoundaryLocation_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polderpeil..
        /// </summary>
        public static string PipingInput_PhreaticLevelExit_Description {
            get {
                return ResourceManager.GetString("PipingInput_PhreaticLevelExit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polderpeil [m+NAP].
        /// </summary>
        public static string PipingInput_PhreaticLevelExit_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_PhreaticLevelExit_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stijghoogte bij uittredepunt..
        /// </summary>
        public static string PipingInput_PiezometricHeadExit_Description {
            get {
                return ResourceManager.GetString("PipingInput_PiezometricHeadExit_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stijghoogte bij uittredepunt [m+NAP].
        /// </summary>
        public static string PipingInput_PiezometricHeadExit_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_PiezometricHeadExit_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzadigd gewicht deklaag..
        /// </summary>
        public static string PipingInput_SaturatedVolumicWeightOfCoverageLayer_Description {
            get {
                return ResourceManager.GetString("PipingInput_SaturatedVolumicWeightOfCoverageLayer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzadigd gewicht deklaag [kN/m³].
        /// </summary>
        public static string PipingInput_SaturatedVolumicWeightOfCoverageLayer_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_SaturatedVolumicWeightOfCoverageLayer_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De horizontale afstand tussen intrede- en uittredepunt die het kwelwater ondergronds aflegt voordat het weer aan de oppervlakte komt..
        /// </summary>
        public static string PipingInput_SeepageLength_Description {
            get {
                return ResourceManager.GetString("PipingInput_SeepageLength_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kwelweglengte [m].
        /// </summary>
        public static string PipingInput_SeepageLength_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_SeepageLength_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De verschillende opbouwen van de ondergrond en hun respectieve kansen van voorkomen..
        /// </summary>
        public static string PipingInput_StochasticSoilModel_Description {
            get {
                return ResourceManager.GetString("PipingInput_StochasticSoilModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stochastisch ondergrondmodel.
        /// </summary>
        public static string PipingInput_StochasticSoilModel_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_StochasticSoilModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De opbouw van de ondergrond..
        /// </summary>
        public static string PipingInput_StochasticSoilProfile_Description {
            get {
                return ResourceManager.GetString("PipingInput_StochasticSoilProfile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondergrondschematisatie.
        /// </summary>
        public static string PipingInput_StochasticSoilProfile_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_StochasticSoilProfile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De schematisatie van de hoogte van het dwarsprofiel..
        /// </summary>
        public static string PipingInput_SurfaceLine_Description {
            get {
                return ResourceManager.GetString("PipingInput_SurfaceLine_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profielschematisatie.
        /// </summary>
        public static string PipingInput_SurfaceLine_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_SurfaceLine_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De dikte van de bovenste voor doorlatendheid te onderscheiden zandlaag of combinatie van zandlagen..
        /// </summary>
        public static string PipingInput_ThicknessAquiferLayer_Description {
            get {
                return ResourceManager.GetString("PipingInput_ThicknessAquiferLayer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dikte watervoerend pakket [m].
        /// </summary>
        public static string PipingInput_ThicknessAquiferLayer_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_ThicknessAquiferLayer_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale deklaagdikte bij uittredepunt..
        /// </summary>
        public static string PipingInput_ThicknessCoverageLayer_Description {
            get {
                return ResourceManager.GetString("PipingInput_ThicknessCoverageLayer_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale deklaagdikte bij uittredepunt [m].
        /// </summary>
        public static string PipingInput_ThicknessCoverageLayer_DisplayName {
            get {
                return ResourceManager.GetString("PipingInput_ThicknessCoverageLayer_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PipingInputIcon {
            get {
                object obj = ResourceManager.GetObject("PipingInputIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kans op heave [1/jaar].
        /// </summary>
        public static string PipingScenarioView_PipingScenarioRow_FailureProbabilityHeave {
            get {
                return ResourceManager.GetString("PipingScenarioView_PipingScenarioRow_FailureProbabilityHeave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faalkans [1/jaar].
        /// </summary>
        public static string PipingScenarioView_PipingScenarioRow_FailureProbabilityPiping {
            get {
                return ResourceManager.GetString("PipingScenarioView_PipingScenarioRow_FailureProbabilityPiping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kans op terugschrijdende erosie [1/jaar].
        /// </summary>
        public static string PipingScenarioView_PipingScenarioRow_FailureProbabilitySellmeijer {
            get {
                return ResourceManager.GetString("PipingScenarioView_PipingScenarioRow_FailureProbabilitySellmeijer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kans op opbarsten [1/jaar].
        /// </summary>
        public static string PipingScenarioView_PipingScenarioRow_FailureProbabilityUplift {
            get {
                return ResourceManager.GetString("PipingScenarioView_PipingScenarioRow_FailureProbabilityUplift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Heave.
        /// </summary>
        public static string PipingSemiProbabilisticOutput_Categories_Heave {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_Categories_Heave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piping.
        /// </summary>
        public static string PipingSemiProbabilisticOutput_Categories_Piping {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_Categories_Piping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Terugschrijdende erosie (Sellmeijer).
        /// </summary>
        public static string PipingSemiProbabilisticOutput_Categories_Sellmeijer {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_Categories_Sellmeijer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opbarsten.
        /// </summary>
        public static string PipingSemiProbabilisticOutput_Categories_Uplift {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_Categories_Uplift", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De veiligheidsfactor voor het submechanisme heave voor deze berekening..
        /// </summary>
        public static string PipingSemiProbabilisticOutput_HeaveFactorOfSafety_Description {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_HeaveFactorOfSafety_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiligheidsfactor [-].
        /// </summary>
        public static string PipingSemiProbabilisticOutput_HeaveFactorOfSafety_DisplayName {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_HeaveFactorOfSafety_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kans dat het submechanisme heave optreedt voor deze berekening..
        /// </summary>
        public static string PipingSemiProbabilisticOutput_HeaveProbability_Description {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_HeaveProbability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kans van voorkomen [1/jaar].
        /// </summary>
        public static string PipingSemiProbabilisticOutput_HeaveProbability_DisplayName {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_HeaveProbability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De betrouwbaarheidsindex voor het submechanisme heave voor deze berekening..
        /// </summary>
        public static string PipingSemiProbabilisticOutput_HeaveReliability_Description {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_HeaveReliability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrouwbaarheidsindex [-].
        /// </summary>
        public static string PipingSemiProbabilisticOutput_HeaveReliability_DisplayName {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_HeaveReliability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De veiligheidsfactor voor deze berekening..
        /// </summary>
        public static string PipingSemiProbabilisticOutput_PipingFactorOfSafety_Description {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_PipingFactorOfSafety_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiligheidsfactor [-].
        /// </summary>
        public static string PipingSemiProbabilisticOutput_PipingFactorOfSafety_DisplayName {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_PipingFactorOfSafety_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De benaderde kans dat het toetsspoor piping optreedt voor deze berekening..
        /// </summary>
        public static string PipingSemiProbabilisticOutput_PipingProbability_Description {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_PipingProbability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benaderde faalkans [1/jaar].
        /// </summary>
        public static string PipingSemiProbabilisticOutput_PipingProbability_DisplayName {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_PipingProbability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De betrouwbaarheidsindex van de faalkans voor deze berekening..
        /// </summary>
        public static string PipingSemiProbabilisticOutput_PipingReliability_Description {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_PipingReliability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrouwbaarheidsindex faalkans [-].
        /// </summary>
        public static string PipingSemiProbabilisticOutput_PipingReliability_DisplayName {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_PipingReliability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De maximaal toegestane kans dat het toetsspoor piping optreedt..
        /// </summary>
        public static string PipingSemiProbabilisticOutput_RequiredProbability_Description {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_RequiredProbability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faalkanseis [1/jaar].
        /// </summary>
        public static string PipingSemiProbabilisticOutput_RequiredProbability_DisplayName {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_RequiredProbability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De betrouwbaarheidsindex van de faalkanseis voor het toetsspoor piping..
        /// </summary>
        public static string PipingSemiProbabilisticOutput_RequiredReliability_Description {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_RequiredReliability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrouwbaarheidsindex faalkanseis [-].
        /// </summary>
        public static string PipingSemiProbabilisticOutput_RequiredReliability_DisplayName {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_RequiredReliability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De veiligheidsfactor voor het submechanisme terugschrijdende erosie (Sellmeijer) voor deze berekening..
        /// </summary>
        public static string PipingSemiProbabilisticOutput_SellmeijerFactorOfSafety_Description {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_SellmeijerFactorOfSafety_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiligheidsfactor [-].
        /// </summary>
        public static string PipingSemiProbabilisticOutput_SellmeijerFactorOfSafety_DisplayName {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_SellmeijerFactorOfSafety_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kans dat het submechanisme terugschrijdende erosie (Sellmeijer) optreedt voor deze berekening..
        /// </summary>
        public static string PipingSemiProbabilisticOutput_SellmeijerProbability_Description {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_SellmeijerProbability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kans van voorkomen [1/jaar].
        /// </summary>
        public static string PipingSemiProbabilisticOutput_SellmeijerProbability_DisplayName {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_SellmeijerProbability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De betrouwbaarheidsindex voor het submechanisme terugschrijdende erosie (Sellmeijer) voor deze berekening..
        /// </summary>
        public static string PipingSemiProbabilisticOutput_SellmeijerReliability_Description {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_SellmeijerReliability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrouwbaarheidsindex [-].
        /// </summary>
        public static string PipingSemiProbabilisticOutput_SellmeijerReliability_DisplayName {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_SellmeijerReliability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De veiligheidsfactor voor het submechanisme opbarsten voor deze berekening..
        /// </summary>
        public static string PipingSemiProbabilisticOutput_UpliftFactorOfSafety_Description {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_UpliftFactorOfSafety_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiligheidsfactor [-].
        /// </summary>
        public static string PipingSemiProbabilisticOutput_UpliftFactorOfSafety_DisplayName {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_UpliftFactorOfSafety_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kans dat het submechanisme opbarsten optreedt voor deze berekening..
        /// </summary>
        public static string PipingSemiProbabilisticOutput_UpliftProbability_Description {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_UpliftProbability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kans van voorkomen [1/jaar].
        /// </summary>
        public static string PipingSemiProbabilisticOutput_UpliftProbability_DisplayName {
            get {
                return ResourceManager.GetString("PipingSemiProbabilisticOutput_UpliftProbability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PipingSoilProfileIcon {
            get {
                object obj = ResourceManager.GetObject("PipingSoilProfileIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap PipingSurfaceLineIcon {
            get {
                object obj = ResourceManager.GetObject("PipingSurfaceLineIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profielschematisaties.
        /// </summary>
        public static string PipingSurfaceLinesCollection_DisplayName {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCollection_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer profielschematisaties.
        /// </summary>
        public static string PipingSurfaceLineSelectionDialog_Select_SurfaceLines {
            get {
                return ResourceManager.GetString("PipingSurfaceLineSelectionDialog_Select_SurfaceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De gemiddelde waarde van de {0}..
        /// </summary>
        public static string Probabilistics_Mean_description_for_Distribution_0_ {
            get {
                return ResourceManager.GetString("Probabilistics_Mean_description_for_Distribution_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verwachtingswaarde.
        /// </summary>
        public static string Probabilistics_Mean_Symbol {
            get {
                return ResourceManager.GetString("Probabilistics_Mean_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De hoeveelheid waarmee de kansverdeling naar rechts (richting van positieve X-as) verschoven is..
        /// </summary>
        public static string Probabilistics_Shift_Description {
            get {
                return ResourceManager.GetString("Probabilistics_Shift_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschuiving.
        /// </summary>
        public static string Probabilistics_Shift_Symbol {
            get {
                return ResourceManager.GetString("Probabilistics_Shift_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De standaardafwijking van de {0}..
        /// </summary>
        public static string Probabilistics_StandardDeviation_description_for_Distribution_0_ {
            get {
                return ResourceManager.GetString("Probabilistics_StandardDeviation_description_for_Distribution_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standaardafwijking.
        /// </summary>
        public static string Probabilistics_StandardDeviation_Symbol {
            get {
                return ResourceManager.GetString("Probabilistics_StandardDeviation_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De locatie van het begin van de slootbodem wanneer deze van de kant van de dijk wordt benaderd..
        /// </summary>
        public static string RingtoetsPipingSurfaceLine_BottomDitchDikeSide_Description {
            get {
                return ResourceManager.GetString("RingtoetsPipingSurfaceLine_BottomDitchDikeSide_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De locatie van het begin van de slootbodem wanneer deze van binnen de polder wordt benaderd..
        /// </summary>
        public static string RingtoetsPipingSurfaceLine_BottomDitchPolderSide_Description {
            get {
                return ResourceManager.GetString("RingtoetsPipingSurfaceLine_BottomDitchPolderSide_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De locatie van de teen van de dijk wanneer de dijk van binnen de polder wordt benaderd..
        /// </summary>
        public static string RingtoetsPipingSurfaceLine_DikeToeAtPolder_Description {
            get {
                return ResourceManager.GetString("RingtoetsPipingSurfaceLine_DikeToeAtPolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De locatie van de teen van de dijk wanneer de dijk van buiten de polder wordt benaderd..
        /// </summary>
        public static string RingtoetsPipingSurfaceLine_DikeToeAtRiver_Description {
            get {
                return ResourceManager.GetString("RingtoetsPipingSurfaceLine_DikeToeAtRiver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profielschematisatie.
        /// </summary>
        public static string RingtoetsPipingSurfaceLine_DisplayName {
            get {
                return ResourceManager.GetString("RingtoetsPipingSurfaceLine_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De locatie van het begin van de sloot wanneer deze van de kant van de dijk wordt benaderd..
        /// </summary>
        public static string RingtoetsPipingSurfaceLine_DitchDikeSide_Description {
            get {
                return ResourceManager.GetString("RingtoetsPipingSurfaceLine_DitchDikeSide_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De locatie van het begin van de sloot wanneer deze van binnen de polder wordt benaderd..
        /// </summary>
        public static string RingtoetsPipingSurfaceLine_DitchPolderSide_Description {
            get {
                return ResourceManager.GetString("RingtoetsPipingSurfaceLine_DitchPolderSide_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam van de profielschematisatie..
        /// </summary>
        public static string RingtoetsPipingSurfaceLine_Name_Description {
            get {
                return ResourceManager.GetString("RingtoetsPipingSurfaceLine_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string RingtoetsPipingSurfaceLine_Name_DisplayName {
            get {
                return ResourceManager.GetString("RingtoetsPipingSurfaceLine_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De punten die de geometrie van de profielschematisatie definiëren..
        /// </summary>
        public static string RingtoetsPipingSurfaceLine_Points_Description {
            get {
                return ResourceManager.GetString("RingtoetsPipingSurfaceLine_Points_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometriepunten.
        /// </summary>
        public static string RingtoetsPipingSurfaceLine_Points_DisplayName {
            get {
                return ResourceManager.GetString("RingtoetsPipingSurfaceLine_Points_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometrie uit de database..
        /// </summary>
        public static string StochasticSoilModel_Geometry_Description {
            get {
                return ResourceManager.GetString("StochasticSoilModel_Geometry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometrie.
        /// </summary>
        public static string StochasticSoilModel_Geometry_DisplayName {
            get {
                return ResourceManager.GetString("StochasticSoilModel_Geometry_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID van het stochastische ondergrondmodel in de database..
        /// </summary>
        public static string StochasticSoilModel_Id_Description {
            get {
                return ResourceManager.GetString("StochasticSoilModel_Id_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ID.
        /// </summary>
        public static string StochasticSoilModel_Id_DisplayName {
            get {
                return ResourceManager.GetString("StochasticSoilModel_Id_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam van het stochastische ondergrondmodel..
        /// </summary>
        public static string StochasticSoilModel_Name_Description {
            get {
                return ResourceManager.GetString("StochasticSoilModel_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string StochasticSoilModel_Name_DisplayName {
            get {
                return ResourceManager.GetString("StochasticSoilModel_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam van het stochastische ondergrondmodel segment..
        /// </summary>
        public static string StochasticSoilModel_SegmentName_Description {
            get {
                return ResourceManager.GetString("StochasticSoilModel_SegmentName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Segment naam.
        /// </summary>
        public static string StochasticSoilModel_SegmentName_DisplayName {
            get {
                return ResourceManager.GetString("StochasticSoilModel_SegmentName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondergrondschematisaties uit de database..
        /// </summary>
        public static string StochasticSoilModel_StochasticSoilProfiles_Description {
            get {
                return ResourceManager.GetString("StochasticSoilModel_StochasticSoilProfiles_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondergrondschematisaties.
        /// </summary>
        public static string StochasticSoilModel_StochasticSoilProfiles_DisplayName {
            get {
                return ResourceManager.GetString("StochasticSoilModel_StochasticSoilProfiles_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stochastische ondergrondmodellen.
        /// </summary>
        public static string StochasticSoilModelCollection_DisplayName {
            get {
                return ResourceManager.GetString("StochasticSoilModelCollection_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StochasticSoilModelIcon {
            get {
                object obj = ResourceManager.GetObject("StochasticSoilModelIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het niveau van de onderkant van de ondergrondschematisatie..
        /// </summary>
        public static string StochasticSoilProfile_Bottom_Description {
            get {
                return ResourceManager.GetString("StochasticSoilProfile_Bottom_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodemniveau.
        /// </summary>
        public static string StochasticSoilProfile_Bottom_DisplayName {
            get {
                return ResourceManager.GetString("StochasticSoilProfile_Bottom_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De naam van de ondergrondschematisatie..
        /// </summary>
        public static string StochasticSoilProfile_Name_Description {
            get {
                return ResourceManager.GetString("StochasticSoilProfile_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string StochasticSoilProfile_Name_DisplayName {
            get {
                return ResourceManager.GetString("StochasticSoilProfile_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het aandeel van de ondergrondschematisatie in het stochastische ondergrondmodel..
        /// </summary>
        public static string StochasticSoilProfile_Probability_Description {
            get {
                return ResourceManager.GetString("StochasticSoilProfile_Probability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aandeel [%].
        /// </summary>
        public static string StochasticSoilProfile_Probability_DisplayName {
            get {
                return ResourceManager.GetString("StochasticSoilProfile_Probability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De niveaus van de bovenkant van de lagen binnen de ondergrondschematisatie..
        /// </summary>
        public static string StochasticSoilProfile_Tops_Description {
            get {
                return ResourceManager.GetString("StochasticSoilProfile_Tops_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Topniveaus.
        /// </summary>
        public static string StochasticSoilProfile_Tops_DisplayName {
            get {
                return ResourceManager.GetString("StochasticSoilProfile_Tops_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het type van de ondergrondschematisatie..
        /// </summary>
        public static string StochasticSoilProfile_Type_Description {
            get {
                return ResourceManager.GetString("StochasticSoilProfile_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string StochasticSoilProfile_Type_DisplayName {
            get {
                return ResourceManager.GetString("StochasticSoilProfile_Type_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondergrondschematisatie.
        /// </summary>
        public static string StochasticSoilProfileProperties_DisplayName {
            get {
                return ResourceManager.GetString("StochasticSoilProfileProperties_DisplayName", resourceCulture);
            }
        }
    }
}
