// Copyright (C) Stichting Deltares 2018. All rights reserved.
//
// This file is part of Ringtoets.
//
// Ringtoets is free software: you can redistribute it and/or modify
// it under the terms of the GNU General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU General Public License for more details.
//
// You should have received a copy of the GNU General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//
// All names, logos, and references to "Deltares" are registered trademarks of
// Stichting Deltares and remain full property of Stichting Deltares at all times.
// All rights reserved.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ringtoets.MacroStabilityInwards.Forms.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ringtoets.MacroStabilityInwards.Forms.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius actieve cirkel.
        /// </summary>
        public static string ActiveCircleRadius_DisplayName {
            get {
                return ResourceManager.GetString("ActiveCircleRadius_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrigeer de stijghoogte in watervoerende zandlaag en tussenzandlaag voor opbarsten?.
        /// </summary>
        public static string AdjustPhreaticLine3And4ForUplift_Description {
            get {
                return ResourceManager.GetString("AdjustPhreaticLine3And4ForUplift_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Corrigeer PL 3 en PL 4 voor opbarsten.
        /// </summary>
        public static string AdjustPhreaticLine3And4ForUplift_DisplayName {
            get {
                return ResourceManager.GetString("AdjustPhreaticLine3And4ForUplift_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grid.
        /// </summary>
        public static string Categories_Grid {
            get {
                return ResourceManager.GetString("Categories_Grid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Macrostabiliteit binnenwaarts.
        /// </summary>
        public static string Categories_MacroStabilityInwards {
            get {
                return ResourceManager.GetString("Categories_MacroStabilityInwards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instellingen.
        /// </summary>
        public static string Categories_Settings {
            get {
                return ResourceManager.GetString("Categories_Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cohesie.
        /// </summary>
        public static string Cohesion_DisplayName {
            get {
                return ResourceManager.GetString("Cohesion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruik zoneringsgrenzen bij het bepalen van het intredepunt van het glijvlak?.
        /// </summary>
        public static string CreateZones_Description {
            get {
                return ResourceManager.GetString("CreateZones_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bepaling.
        /// </summary>
        public static string CreateZones_DisplayName {
            get {
                return ResourceManager.GetString("CreateZones_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dagelijkse omstandigheden.
        /// </summary>
        public static string Daily_DisplayName {
            get {
                return ResourceManager.GetString("Daily_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dijktype van de geschematiseerde dijk..
        /// </summary>
        public static string DikeSoilScenario_Description {
            get {
                return ResourceManager.GetString("DikeSoilScenario_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dijk/bodem materiaal.
        /// </summary>
        public static string DikeSoilScenario_DisplayName {
            get {
                return ResourceManager.GetString("DikeSoilScenario_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschappen van drainage constructie..
        /// </summary>
        public static string DrainageConstruction_Description {
            get {
                return ResourceManager.GetString("DrainageConstruction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Drainage.
        /// </summary>
        public static string DrainageConstruction_DisplayName {
            get {
                return ResourceManager.GetString("DrainageConstruction_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is drainage aanwezig?.
        /// </summary>
        public static string DrainageConstructionPresent_Description {
            get {
                return ResourceManager.GetString("DrainageConstructionPresent_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aanwezig.
        /// </summary>
        public static string DrainageConstructionPresent_DisplayName {
            get {
                return ResourceManager.GetString("DrainageConstructionPresent_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extreme omstandigheden.
        /// </summary>
        public static string Extreme_DisplayName {
            get {
                return ResourceManager.GetString("Extreme_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrijvingshoek.
        /// </summary>
        public static string FrictionAngle_DisplayName {
            get {
                return ResourceManager.GetString("FrictionAngle_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekengrid automatisch bepalen of handmatig invoeren?.
        /// </summary>
        public static string GridDeterminationType_Description {
            get {
                return ResourceManager.GetString("GridDeterminationType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bepaling grid.
        /// </summary>
        public static string GridDeterminationType_DisplayName {
            get {
                return ResourceManager.GetString("GridDeterminationType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschappen van de rekengrids..
        /// </summary>
        public static string GridSettings_Description {
            get {
                return ResourceManager.GetString("GridSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rekengrids.
        /// </summary>
        public static string GridSettings_DisplayName {
            get {
                return ResourceManager.GetString("GridSettings_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lengtemaat die uitdrukking geeft aan de afstand waarover de stijghoogte verloopt in de diepe watervoerende zandlaag ter hoogte van het achterland..
        /// </summary>
        public static string LeakageLengthInwardsPhreaticLine3_Description {
            get {
                return ResourceManager.GetString("LeakageLengthInwardsPhreaticLine3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leklengte binnenwaarts PL 3 [m].
        /// </summary>
        public static string LeakageLengthInwardsPhreaticLine3_DisplayName {
            get {
                return ResourceManager.GetString("LeakageLengthInwardsPhreaticLine3_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lengtemaat die uitdrukking geeft aan de afstand waarover de stijghoogte verloopt in de tussenzandlaag ter hoogte van het achterland..
        /// </summary>
        public static string LeakageLengthInwardsPhreaticLine4_Description {
            get {
                return ResourceManager.GetString("LeakageLengthInwardsPhreaticLine4_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leklengte binnenwaarts PL 4 [m].
        /// </summary>
        public static string LeakageLengthInwardsPhreaticLine4_DisplayName {
            get {
                return ResourceManager.GetString("LeakageLengthInwardsPhreaticLine4_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lengtemaat die uitdrukking geeft aan de afstand waarover de stijghoogte verloopt in de diepe watervoerende zandlaag ter hoogte van het voorland..
        /// </summary>
        public static string LeakageLengthOutwardsPhreaticLine3_Description {
            get {
                return ResourceManager.GetString("LeakageLengthOutwardsPhreaticLine3_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leklengte buitenwaarts PL 3 [m].
        /// </summary>
        public static string LeakageLengthOutwardsPhreaticLine3_DisplayName {
            get {
                return ResourceManager.GetString("LeakageLengthOutwardsPhreaticLine3_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lengtemaat die uitdrukking geeft aan de afstand waarover de stijghoogte verloopt in de tussenzandlaag ter hoogte van het voorland..
        /// </summary>
        public static string LeakageLengthOutwardsPhreaticLine4_Description {
            get {
                return ResourceManager.GetString("LeakageLengthOutwardsPhreaticLine4_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Leklengte buitenwaarts PL 4 [m].
        /// </summary>
        public static string LeakageLengthOutwardsPhreaticLine4_DisplayName {
            get {
                return ResourceManager.GetString("LeakageLengthOutwardsPhreaticLine4_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschappen van het linker grid..
        /// </summary>
        public static string LeftGrid_Description {
            get {
                return ResourceManager.GetString("LeftGrid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linker grid.
        /// </summary>
        public static string LeftGrid_DisplayName {
            get {
                return ResourceManager.GetString("LeftGrid_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometrie.
        /// </summary>
        public static string Line_Geometry_DisplayName {
            get {
                return ResourceManager.GetString("Line_Geometry_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Line_Name_DisplayName {
            get {
                return ResourceManager.GetString("Line_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschappen van de waterspanningen bij dagelijkse omstandigheden..
        /// </summary>
        public static string LocationDaily_Description {
            get {
                return ResourceManager.GetString("LocationDaily_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschappen van de waterspanningen bij extreme omstandigheden..
        /// </summary>
        public static string LocationExtreme_Description {
            get {
                return ResourceManager.GetString("LocationExtreme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string MacroStabilityInwardsCalculation_Name_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsCalculation_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen ondergrondschematisaties gevonden voor profielschematisatie &apos;{0}&apos;. De profielschematisatie is overgeslagen..
        /// </summary>
        public static string MacroStabilityInwardsCalculationConfigurationHelper_GenerateCalculationsStructure_No_SoilProfile_found_for_MacroStabilityInwardsSurfaceLine_0_skipped {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsCalculationConfigurationHelper_GenerateCalculationsStructure" +
                        "_No_SoilProfile_found_for_MacroStabilityInwardsSurfaceLine_0_skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er zijn geen profielschematisaties of stochastische ondergrondmodellen beschikbaar om berekeningen voor te genereren..
        /// </summary>
        public static string MacroStabilityInwardsCalculationGroup_Generate_MacroStabilityInwardsCalculations_NoSurfaceLinesOrSoilModels_ToolTip {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsCalculationGroup_Generate_MacroStabilityInwardsCalculations_" +
                        "NoSurfaceLinesOrSoilModels_ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Genereer scenario&apos;s op basis van geselecteerde profielschematisaties..
        /// </summary>
        public static string MacroStabilityInwardsCalculationGroup_Generate_MacroStabilityInwardsCalculations_ToolTip {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsCalculationGroup_Generate_MacroStabilityInwardsCalculations_" +
                        "ToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bijdrage aan
        ///scenario
        ///[%].
        /// </summary>
        public static string MacroStabilityInwardsCalculationsView_InitializeDataGridView_Contribution {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsCalculationsView_InitializeDataGridView_Contribution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In oordeel.
        /// </summary>
        public static string MacroStabilityInwardsCalculationsView_InitializeDataGridView_In_final_rating {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsCalculationsView_InitializeDataGridView_In_final_rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aandeel van schematisatie
        ///in het stochastische ondergrondmodel
        ///[%].
        /// </summary>
        public static string MacroStabilityInwardsCalculationsView_InitializeDataGridView_Stochastic_soil_profile_probability {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsCalculationsView_InitializeDataGridView_Stochastic_soil_prof" +
                        "ile_probability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelfactor die wordt gebruikt bij de berekening van de benaderde faalkans op basis van de berekende stabiliteitsfactor..
        /// </summary>
        public static string MacroStabilityInwardsFailureMechanismProperties_ModelFactor_Description {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsFailureMechanismProperties_ModelFactor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modelfactor [-].
        /// </summary>
        public static string MacroStabilityInwardsFailureMechanismProperties_ModelFactor_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsFailureMechanismProperties_ModelFactor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De verschillende opbouwen van de ondergrond en hun respectievelijke kansen van voorkomen..
        /// </summary>
        public static string MacroStabilityInwardsInput_StochasticSoilModel_Description {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsInput_StochasticSoilModel_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stochastisch ondergrondmodel.
        /// </summary>
        public static string MacroStabilityInwardsInput_StochasticSoilModel_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsInput_StochasticSoilModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De opbouw van de ondergrond..
        /// </summary>
        public static string MacroStabilityInwardsInput_StochasticSoilProfile_Description {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsInput_StochasticSoilProfile_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondergrondschematisatie.
        /// </summary>
        public static string MacroStabilityInwardsInput_StochasticSoilProfile_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsInput_StochasticSoilProfile_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het quotiënt van de weerstandbiedende- en aandrijvende krachten langs een glijvlak..
        /// </summary>
        public static string MacroStabilityInwardsOutput_FactorOfStability_Description {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsOutput_FactorOfStability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stabiliteitsfactor [-].
        /// </summary>
        public static string MacroStabilityInwardsOutput_FactorOfStability_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsOutput_FactorOfStability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De veiligheidsfactor voor deze berekening..
        /// </summary>
        public static string MacroStabilityInwardsOutput_MacroStabilityInwardsFactorOfSafety_Description {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsOutput_MacroStabilityInwardsFactorOfSafety_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Veiligheidsfactor [-].
        /// </summary>
        public static string MacroStabilityInwardsOutput_MacroStabilityInwardsFactorOfSafety_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsOutput_MacroStabilityInwardsFactorOfSafety_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De benaderde kans dat het toetsspoor macrostabiliteit binnenwaarts optreedt voor deze berekening..
        /// </summary>
        public static string MacroStabilityInwardsOutput_MacroStabilityInwardsProbability_Description {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsOutput_MacroStabilityInwardsProbability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Benaderde faalkans [1/jaar].
        /// </summary>
        public static string MacroStabilityInwardsOutput_MacroStabilityInwardsProbability_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsOutput_MacroStabilityInwardsProbability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De betrouwbaarheidsindex van de faalkans voor deze berekening..
        /// </summary>
        public static string MacroStabilityInwardsOutput_MacroStabilityInwardsReliability_Description {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsOutput_MacroStabilityInwardsReliability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrouwbaarheidsindex faalkans [-].
        /// </summary>
        public static string MacroStabilityInwardsOutput_MacroStabilityInwardsReliability_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsOutput_MacroStabilityInwardsReliability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De maximaal toegestane kans dat het toetsspoor macrostabiliteit binnenwaarts optreedt..
        /// </summary>
        public static string MacroStabilityInwardsOutput_RequiredProbability_Description {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsOutput_RequiredProbability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faalkanseis [1/jaar].
        /// </summary>
        public static string MacroStabilityInwardsOutput_RequiredProbability_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsOutput_RequiredProbability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De betrouwbaarheidsindex van de faalkanseis voor het toetsspoor macrostabiliteit binnenwaarts..
        /// </summary>
        public static string MacroStabilityInwardsOutput_RequiredReliability_Description {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsOutput_RequiredReliability_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Betrouwbaarheidsindex faalkanseis [-].
        /// </summary>
        public static string MacroStabilityInwardsOutput_RequiredReliability_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsOutput_RequiredReliability_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grensspanning op de aangegeven locatie..
        /// </summary>
        public static string MacroStabilityInwardsPreconsolidationStress_PreconsolidationStress_Description {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsPreconsolidationStress_PreconsolidationStress_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grensspanning [kN/m²].
        /// </summary>
        public static string MacroStabilityInwardsPreconsolidationStress_PreconsolidationStress_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsPreconsolidationStress_PreconsolidationStress_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokale x-coördinaat van het punt waarvoor de grensspanning is opgegeven..
        /// </summary>
        public static string MacroStabilityInwardsPreconsolidationStress_XCoordinate_Description {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsPreconsolidationStress_XCoordinate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X [m].
        /// </summary>
        public static string MacroStabilityInwardsPreconsolidationStress_XCoordinate_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsPreconsolidationStress_XCoordinate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokale z-coördinaat van het punt waarvoor de grensspanning is opgegeven..
        /// </summary>
        public static string MacroStabilityInwardsPreconsolidationStress_ZCoordinate_Description {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsPreconsolidationStress_ZCoordinate_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z [m+NAP].
        /// </summary>
        public static string MacroStabilityInwardsPreconsolidationStress_ZCoordinate_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsPreconsolidationStress_ZCoordinate_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Faalkans
        ///[1/jaar].
        /// </summary>
        public static string MacroStabilityInwardsScenarioView_MacroStabilityInwardsScenarioRow_MacroStabilityInwardsProbability {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsScenarioView_MacroStabilityInwardsScenarioRow_MacroStability" +
                        "InwardsProbability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Booglengte.
        /// </summary>
        public static string MacroStabilityInwardsSlice_ArcLength_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_ArcLength_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bodemhoek.
        /// </summary>
        public static string MacroStabilityInwardsSlice_BottomAngle_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_BottomAngle_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effectieve spanning.
        /// </summary>
        public static string MacroStabilityInwardsSlice_EffectiveStress_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_EffectiveStress_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effectieve spanning (dagelijks).
        /// </summary>
        public static string MacroStabilityInwardsSlice_EffectiveStressDaily_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_EffectiveStressDaily_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontale waterspanning op maaiveld.
        /// </summary>
        public static string MacroStabilityInwardsSlice_HorizontalPorePressure_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_HorizontalPorePressure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spanning belasting.
        /// </summary>
        public static string MacroStabilityInwardsSlice_LoadStress_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_LoadStress_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string MacroStabilityInwardsSlice_Name_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normaalspanning.
        /// </summary>
        public static string MacroStabilityInwardsSlice_NormalStress_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_NormalStress_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OCR.
        /// </summary>
        public static string MacroStabilityInwardsSlice_OverConsolidationRatio_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_OverConsolidationRatio_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piezometrische waterspanning.
        /// </summary>
        public static string MacroStabilityInwardsSlice_PiezometricPorePressure_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_PiezometricPorePressure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterspanning op maaiveld.
        /// </summary>
        public static string MacroStabilityInwardsSlice_PorePressure_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_PorePressure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schuifspanning.
        /// </summary>
        public static string MacroStabilityInwardsSlice_ShearStress_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_ShearStress_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tophoek.
        /// </summary>
        public static string MacroStabilityInwardsSlice_TopAngle_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_TopAngle_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale waterspanning.
        /// </summary>
        public static string MacroStabilityInwardsSlice_TotalPorePressure_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_TotalPorePressure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verticale waterspanning op maaiveld.
        /// </summary>
        public static string MacroStabilityInwardsSlice_VerticalPorePressure_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_VerticalPorePressure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewicht.
        /// </summary>
        public static string MacroStabilityInwardsSlice_Weight_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_Weight_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Breedte.
        /// </summary>
        public static string MacroStabilityInwardsSlice_Width_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_Width_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X centrum.
        /// </summary>
        public static string MacroStabilityInwardsSlice_XCenter_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_XCenter_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z centrum bodem.
        /// </summary>
        public static string MacroStabilityInwardsSlice_ZCenterBottom_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlice_ZCenterBottom_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Effectieve spanning
        ///(dagelijks).
        /// </summary>
        public static string MacroStabilityInwardsSlicesTable_EffectiveStressDaily_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlicesTable_EffectiveStressDaily_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontale waterspanning
        ///op maaiveld.
        /// </summary>
        public static string MacroStabilityInwardsSlicesTable_HorizontalPorePressure_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlicesTable_HorizontalPorePressure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamel {0}.
        /// </summary>
        public static string MacroStabilityInwardsSlicesTable_Name_Slice_0 {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlicesTable_Name_Slice_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Piezometrische
        ///waterspanning.
        /// </summary>
        public static string MacroStabilityInwardsSlicesTable_PiezometricPorePressure_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlicesTable_PiezometricPorePressure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterspanning
        ///op maaiveld.
        /// </summary>
        public static string MacroStabilityInwardsSlicesTable_PorePressure_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlicesTable_PorePressure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totale
        ///waterspanning.
        /// </summary>
        public static string MacroStabilityInwardsSlicesTable_TotalPorePressure_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlicesTable_TotalPorePressure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verticale waterspanning
        ///op maaiveld.
        /// </summary>
        public static string MacroStabilityInwardsSlicesTable_VerticalPorePressure_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSlicesTable_VerticalPorePressure_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Onverzadigd gewicht.
        /// </summary>
        public static string MacroStabilityInwardsSoilLayerData_AbovePhreaticLevel_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSoilLayerData_AbovePhreaticLevel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verzadigd gewicht.
        /// </summary>
        public static string MacroStabilityInwardsSoilLayerData_BelowPhreaticLevel_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSoilLayerData_BelowPhreaticLevel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleur.
        /// </summary>
        public static string MacroStabilityInwardsSoilLayerData_Color_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSoilLayerData_Color_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Is aquifer.
        /// </summary>
        public static string MacroStabilityInwardsSoilLayerData_IsAquifer_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSoilLayerData_IsAquifer_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string MacroStabilityInwardsSoilLayerData_MaterialName_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSoilLayerData_MaterialName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schuifsterkte model.
        /// </summary>
        public static string MacroStabilityInwardsSoilLayerData_ShearStrengthModel_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSoilLayerData_ShearStrengthModel_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schuifsterkte ratio (S).
        /// </summary>
        public static string MacroStabilityInwardsSoilLayerData_ShearStrengthRatio_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSoilLayerData_ShearStrengthRatio_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sterkte toename exp (m).
        /// </summary>
        public static string MacroStabilityInwardsSoilLayerData_StrengthIncreaseExponent_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSoilLayerData_StrengthIncreaseExponent_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruik POP.
        /// </summary>
        public static string MacroStabilityInwardsSoilLayerData_UsePop_DisplayName {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSoilLayerData_UsePop_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De locatie van het bestand waaruit de profielschematisaties zijn geïmporteerd..
        /// </summary>
        public static string MacroStabilityInwardsSurfaceLineCollection_SourcePath_Description {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSurfaceLineCollection_SourcePath_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selecteer profielschematisaties.
        /// </summary>
        public static string MacroStabilityInwardsSurfaceLineSelectionDialog_Select_SurfaceLines {
            get {
                return ResourceManager.GetString("MacroStabilityInwardsSurfaceLineSelectionDialog_Select_SurfaceLines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximale breedte van een lamel..
        /// </summary>
        public static string MaximumSliceWidth_Description {
            get {
                return ResourceManager.GetString("MaximumSliceWidth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximale lamelbreedte [m].
        /// </summary>
        public static string MaximumSliceWidth_DisplayName {
            get {
                return ResourceManager.GetString("MaximumSliceWidth_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimale hoogte van de freatische lijn onder kruin binnentalud..
        /// </summary>
        public static string MinimumLevelPhreaticLineAtDikeTopPolder_Description {
            get {
                return ResourceManager.GetString("MinimumLevelPhreaticLineAtDikeTopPolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL 1 initiële hoogte onder binnenkruin [m+NAP].
        /// </summary>
        public static string MinimumLevelPhreaticLineAtDikeTopPolder_DisplayName {
            get {
                return ResourceManager.GetString("MinimumLevelPhreaticLineAtDikeTopPolder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimale hoogte van de freatische lijn onder kruin buitentalud..
        /// </summary>
        public static string MinimumLevelPhreaticLineAtDikeTopRiver_Description {
            get {
                return ResourceManager.GetString("MinimumLevelPhreaticLineAtDikeTopRiver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL 1 initiële hoogte onder buitenkruin [m+NAP].
        /// </summary>
        public static string MinimumLevelPhreaticLineAtDikeTopRiver_DisplayName {
            get {
                return ResourceManager.GetString("MinimumLevelPhreaticLineAtDikeTopRiver_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sta automatische aanpassing van het grid toe?.
        /// </summary>
        public static string MoveGrid_Description {
            get {
                return ResourceManager.GetString("MoveGrid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verplaats grid.
        /// </summary>
        public static string MoveGrid_DisplayName {
            get {
                return ResourceManager.GetString("MoveGrid_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal punten waarmee het grid wordt samengesteld in horizontale richting..
        /// </summary>
        public static string NumberOfHorizontalPoints_Description {
            get {
                return ResourceManager.GetString("NumberOfHorizontalPoints_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal horizontale punten.
        /// </summary>
        public static string NumberOfHorizontalPoints_DisplayName {
            get {
                return ResourceManager.GetString("NumberOfHorizontalPoints_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal punten waarmee het grid wordt samengesteld in verticale richting..
        /// </summary>
        public static string NumberOfVerticalPoints_Description {
            get {
                return ResourceManager.GetString("NumberOfVerticalPoints_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal verticale punten.
        /// </summary>
        public static string NumberOfVerticalPoints_DisplayName {
            get {
                return ResourceManager.GetString("NumberOfVerticalPoints_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschappen van offsets PL 1..
        /// </summary>
        public static string Offsets_Description {
            get {
                return ResourceManager.GetString("Offsets_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offsets PL 1.
        /// </summary>
        public static string Offsets_DisplayName {
            get {
                return ResourceManager.GetString("Offsets_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Radius passieve cirkel.
        /// </summary>
        public static string PassiveCircleRadius_DisplayName {
            get {
                return ResourceManager.GetString("PassiveCircleRadius_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De verticale afstand waarover de waterspanning in de deklaag verandert bij waterspanningsvariaties in de watervoerende zandlaag..
        /// </summary>
        public static string PenetrationLength_Description {
            get {
                return ResourceManager.GetString("PenetrationLength_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indringingslengte [m].
        /// </summary>
        public static string PenetrationLength_DisplayName {
            get {
                return ResourceManager.GetString("PenetrationLength_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterstandsverschil tussen het maaiveld en de freatische lijn onder teen dijk binnenwaarts..
        /// </summary>
        public static string PhreaticLineOffsetBelowDikeToeAtPolder_Description {
            get {
                return ResourceManager.GetString("PhreaticLineOffsetBelowDikeToeAtPolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL 1 offset onder teen dijk binnenwaarts [m].
        /// </summary>
        public static string PhreaticLineOffsetBelowDikeToeAtPolder_DisplayName {
            get {
                return ResourceManager.GetString("PhreaticLineOffsetBelowDikeToeAtPolder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschil tussen de waterstand en de freatische lijn onder kruin binnentalud..
        /// </summary>
        public static string PhreaticLineOffsetBelowDikeTopAtPolder_Description {
            get {
                return ResourceManager.GetString("PhreaticLineOffsetBelowDikeTopAtPolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL 1 offset onder binnenkruin [m].
        /// </summary>
        public static string PhreaticLineOffsetBelowDikeTopAtPolder_DisplayName {
            get {
                return ResourceManager.GetString("PhreaticLineOffsetBelowDikeTopAtPolder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verschil tussen de waterstand en de freatische lijn onder kruin buitentalud..
        /// </summary>
        public static string PhreaticLineOffsetBelowDikeTopAtRiver_Description {
            get {
                return ResourceManager.GetString("PhreaticLineOffsetBelowDikeTopAtRiver_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL 1 offset onder buitenkruin [m].
        /// </summary>
        public static string PhreaticLineOffsetBelowDikeTopAtRiver_DisplayName {
            get {
                return ResourceManager.GetString("PhreaticLineOffsetBelowDikeTopAtRiver_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterstandsverschil tussen het maaiveld en de freatische lijn onder insteek binnenberm..
        /// </summary>
        public static string PhreaticLineOffsetBelowShoulderBaseInside_Description {
            get {
                return ResourceManager.GetString("PhreaticLineOffsetBelowShoulderBaseInside_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PL 1 offset onder insteek binnenberm [m].
        /// </summary>
        public static string PhreaticLineOffsetBelowShoulderBaseInside_DisplayName {
            get {
                return ResourceManager.GetString("PhreaticLineOffsetBelowShoulderBaseInside_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stijghoogte in de indringingslaag binnenwaarts..
        /// </summary>
        public static string PiezometricHeadPhreaticLine2Inwards_Description {
            get {
                return ResourceManager.GetString("PiezometricHeadPhreaticLine2Inwards_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stijghoogte PL 2 binnenwaarts [m+NAP].
        /// </summary>
        public static string PiezometricHeadPhreaticLine2Inwards_DisplayName {
            get {
                return ResourceManager.GetString("PiezometricHeadPhreaticLine2Inwards_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stijghoogte in de indringingslaag buitenwaarts..
        /// </summary>
        public static string PiezometricHeadPhreaticLine2Outwards_Description {
            get {
                return ResourceManager.GetString("PiezometricHeadPhreaticLine2Outwards_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stijghoogte PL 2 buitenwaarts [m+NAP].
        /// </summary>
        public static string PiezometricHeadPhreaticLine2Outwards_DisplayName {
            get {
                return ResourceManager.GetString("PiezometricHeadPhreaticLine2Outwards_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De geometrie van de lijn..
        /// </summary>
        public static string PiezometricLine_Geometry_Description {
            get {
                return ResourceManager.GetString("PiezometricLine_Geometry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De naam van de lijn..
        /// </summary>
        public static string PiezometricLine_Name_Description {
            get {
                return ResourceManager.GetString("PiezometricLine_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to POP.
        /// </summary>
        public static string Pop_DisplayName {
            get {
                return ResourceManager.GetString("Pop_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De grensspanningen in de ondergrondschematisatie..
        /// </summary>
        public static string PreconsolidationStresses_Description {
            get {
                return ResourceManager.GetString("PreconsolidationStresses_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grensspanningen.
        /// </summary>
        public static string PreconsolidationStresses_DisplayName {
            get {
                return ResourceManager.GetString("PreconsolidationStresses_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschappen van het rechter grid..
        /// </summary>
        public static string RightGrid_Description {
            get {
                return ResourceManager.GetString("RightGrid_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechter grid.
        /// </summary>
        public static string RightGrid_DisplayName {
            get {
                return ResourceManager.GetString("RightGrid_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitvoer per lamel.
        /// </summary>
        public static string SliceParameters_DisplayName {
            get {
                return ResourceManager.GetString("SliceParameters_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lamellen.
        /// </summary>
        public static string Slices_DisplayName {
            get {
                return ResourceManager.GetString("Slices_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Glijvlak.
        /// </summary>
        public static string SlipPlane_DisplayName {
            get {
                return ResourceManager.GetString("SlipPlane_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimale diepte van het berekende glijvlak ten opzichte van het maaiveld..
        /// </summary>
        public static string SlipPlaneMinimumDepth_Description {
            get {
                return ResourceManager.GetString("SlipPlaneMinimumDepth_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimale glijvlakdiepte [m].
        /// </summary>
        public static string SlipPlaneMinimumDepth_DisplayName {
            get {
                return ResourceManager.GetString("SlipPlaneMinimumDepth_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimale lengte van het berekende glijvlak..
        /// </summary>
        public static string SlipPlaneMinimumLength_Description {
            get {
                return ResourceManager.GetString("SlipPlaneMinimumLength_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimale glijvlaklengte [m].
        /// </summary>
        public static string SlipPlaneMinimumLength_DisplayName {
            get {
                return ResourceManager.GetString("SlipPlaneMinimumLength_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschappen van de zonering van het glijvlak..
        /// </summary>
        public static string SlipPlaneSettings_Description {
            get {
                return ResourceManager.GetString("SlipPlaneSettings_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zonering glijvlak.
        /// </summary>
        public static string SlipPlaneSettings_DisplayName {
            get {
                return ResourceManager.GetString("SlipPlaneSettings_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De geometrie van de buitenring van deze grondlaag..
        /// </summary>
        public static string SoilLayer_Geometry_Description {
            get {
                return ResourceManager.GetString("SoilLayer_Geometry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geometrie.
        /// </summary>
        public static string SoilLayer_Geometry_DisplayName {
            get {
                return ResourceManager.GetString("SoilLayer_Geometry_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De uitsneden binnen deze grondlaag..
        /// </summary>
        public static string SoilLayer_NestedLayers_Description {
            get {
                return ResourceManager.GetString("SoilLayer_NestedLayers_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uitsneden.
        /// </summary>
        public static string SoilLayer_NestedLayers_DisplayName {
            get {
                return ResourceManager.GetString("SoilLayer_NestedLayers_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SoilProfileIcon {
            get {
                object obj = ResourceManager.GetObject("SoilProfileIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap StochasticSoilModelIcon {
            get {
                object obj = ResourceManager.GetObject("StochasticSoilModelIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap SurfaceLineIcon {
            get {
                object obj = ResourceManager.GetObject("SurfaceLineIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bepaling raaklijnen op basis van grondlaagscheidingen of handmatig?.
        /// </summary>
        public static string TangentLineDeterminationType_Description {
            get {
                return ResourceManager.GetString("TangentLineDeterminationType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bepaling tangentlijnen.
        /// </summary>
        public static string TangentLineDeterminationType_DisplayName {
            get {
                return ResourceManager.GetString("TangentLineDeterminationType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het aantal raaklijnen dat bepaald moet worden..
        /// </summary>
        public static string TangentLineNumber_Description {
            get {
                return ResourceManager.GetString("TangentLineNumber_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aantal tangentlijnen.
        /// </summary>
        public static string TangentLineNumber_DisplayName {
            get {
                return ResourceManager.GetString("TangentLineNumber_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangentlijnen.
        /// </summary>
        public static string TangentLines_DisplayName {
            get {
                return ResourceManager.GetString("TangentLines_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verticale coördinaat van de onderste raaklijn..
        /// </summary>
        public static string TangentLineZBottom_Description {
            get {
                return ResourceManager.GetString("TangentLineZBottom_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangentlijn Z-onder [m+NAP].
        /// </summary>
        public static string TangentLineZBottom_DisplayName {
            get {
                return ResourceManager.GetString("TangentLineZBottom_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verticale coördinaat van de bovenste raaklijn..
        /// </summary>
        public static string TangentLineZTop_Description {
            get {
                return ResourceManager.GetString("TangentLineZTop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tangentlijn Z-boven [m+NAP].
        /// </summary>
        public static string TangentLineZTop_DisplayName {
            get {
                return ResourceManager.GetString("TangentLineZTop_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [°].
        /// </summary>
        public static string Unit_Degree {
            get {
                return ResourceManager.GetString("Unit_Degree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [kN/m³].
        /// </summary>
        public static string Unit_KiloNewtonPerCubicMeter {
            get {
                return ResourceManager.GetString("Unit_KiloNewtonPerCubicMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [kN/m].
        /// </summary>
        public static string Unit_KiloNewtonPerMeter {
            get {
                return ResourceManager.GetString("Unit_KiloNewtonPerMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [kN/m²].
        /// </summary>
        public static string Unit_KiloNewtonPerSquareMeter {
            get {
                return ResourceManager.GetString("Unit_KiloNewtonPerSquareMeter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [m].
        /// </summary>
        public static string Unit_Meter {
            get {
                return ResourceManager.GetString("Unit_Meter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [m+NAP].
        /// </summary>
        public static string Unit_MeterAboveNAP {
            get {
                return ResourceManager.GetString("Unit_MeterAboveNAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to [-].
        /// </summary>
        public static string Unit_None {
            get {
                return ResourceManager.GetString("Unit_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruik standaard waterstandsverschillen voor het bepalen van de freatische lijn?.
        /// </summary>
        public static string UseDefaultOffsets_Description {
            get {
                return ResourceManager.GetString("UseDefaultOffsets_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gebruik default waarden voor offsets van PL 1.
        /// </summary>
        public static string UseDefaultOffsets_DisplayName {
            get {
                return ResourceManager.GetString("UseDefaultOffsets_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het niveau van het oppervlaktewater binnen een beheersgebied..
        /// </summary>
        public static string WaterLevelPolder_Description {
            get {
                return ResourceManager.GetString("WaterLevelPolder_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polderpeil [m+NAP].
        /// </summary>
        public static string WaterLevelPolder_DisplayName {
            get {
                return ResourceManager.GetString("WaterLevelPolder_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemiddeld hoog water..
        /// </summary>
        public static string WaterLevelRiverAverage_Description {
            get {
                return ResourceManager.GetString("WaterLevelRiverAverage_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gemiddeld hoog water (GHW) [m+NAP].
        /// </summary>
        public static string WaterLevelRiverAverage_DisplayName {
            get {
                return ResourceManager.GetString("WaterLevelRiverAverage_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschappen van de stijghoogtelijnen..
        /// </summary>
        public static string Waternet_PiezometricLines_Description {
            get {
                return ResourceManager.GetString("Waternet_PiezometricLines_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stijghoogtelijnen.
        /// </summary>
        public static string Waternet_PiezometricLines_DisplayName {
            get {
                return ResourceManager.GetString("Waternet_PiezometricLines_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschappen van de zones..
        /// </summary>
        public static string Waternet_WaternetLines_Description {
            get {
                return ResourceManager.GetString("Waternet_WaternetLines_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones.
        /// </summary>
        public static string Waternet_WaternetLines_DisplayName {
            get {
                return ResourceManager.GetString("Waternet_WaternetLines_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De geometrie van de zone..
        /// </summary>
        public static string WaternetLine_Geometry_Description {
            get {
                return ResourceManager.GetString("WaternetLine_Geometry_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De naam van de zone..
        /// </summary>
        public static string WaternetLine_Name_Description {
            get {
                return ResourceManager.GetString("WaternetLine_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De stijghoogtelijn behorend bij de zone..
        /// </summary>
        public static string WaternetLine_PiezometricLineName_Description {
            get {
                return ResourceManager.GetString("WaternetLine_PiezometricLineName_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stijghoogtelijn.
        /// </summary>
        public static string WaternetLine_PiezometricLineName_DisplayName {
            get {
                return ResourceManager.GetString("WaternetLine_PiezometricLineName_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones dagelijks.
        /// </summary>
        public static string WaternetLinesDaily_DisplayName {
            get {
                return ResourceManager.GetString("WaternetLinesDaily_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zones extreem.
        /// </summary>
        public static string WaternetLinesExtreme_DisplayName {
            get {
                return ResourceManager.GetString("WaternetLinesExtreme_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschappen van de waterspanning..
        /// </summary>
        public static string Waterstresses_Description {
            get {
                return ResourceManager.GetString("Waterstresses_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterspanningen.
        /// </summary>
        public static string Waterstresses_DisplayName {
            get {
                return ResourceManager.GetString("Waterstresses_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschappen van de waterspanningslijnen bij dagelijkse omstandigheden..
        /// </summary>
        public static string WaterStressLines_Daily_Description {
            get {
                return ResourceManager.GetString("WaterStressLines_Daily_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschappen van de waterspanningslijnen..
        /// </summary>
        public static string WaterStressLines_Description {
            get {
                return ResourceManager.GetString("WaterStressLines_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Waterspanningslijnen.
        /// </summary>
        public static string WaterStressLines_DisplayName {
            get {
                return ResourceManager.GetString("WaterStressLines_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eigenschappen van de waterspanningslijnen bij extreme omstandigheden..
        /// </summary>
        public static string WaterStressLines_Extreme_Description {
            get {
                return ResourceManager.GetString("WaterStressLines_Extreme_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X-coördinaat van het middelpunt van de drainage (in lokale coördinaten)..
        /// </summary>
        public static string XCoordinateDrainageConstruction_Description {
            get {
                return ResourceManager.GetString("XCoordinateDrainageConstruction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X [m].
        /// </summary>
        public static string XCoordinateDrainageConstruction_DisplayName {
            get {
                return ResourceManager.GetString("XCoordinateDrainageConstruction_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontale coördinaat van de linker kant van het rekengrid..
        /// </summary>
        public static string XLeft_Description {
            get {
                return ResourceManager.GetString("XLeft_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X links [m].
        /// </summary>
        public static string XLeft_DisplayName {
            get {
                return ResourceManager.GetString("XLeft_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Horizontale coördinaat van de rechter kant van het rekengrid..
        /// </summary>
        public static string XRight_Description {
            get {
                return ResourceManager.GetString("XRight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to X rechts [m].
        /// </summary>
        public static string XRight_DisplayName {
            get {
                return ResourceManager.GetString("XRight_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verticale coördinaat van de onderkant van het rekengrid..
        /// </summary>
        public static string ZBottom_Description {
            get {
                return ResourceManager.GetString("ZBottom_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z onder [m+NAP].
        /// </summary>
        public static string ZBottom_DisplayName {
            get {
                return ResourceManager.GetString("ZBottom_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z-coördinaat (hoogte) van het middelpunt van de drainage..
        /// </summary>
        public static string ZCoordinateDrainageConstruction_Description {
            get {
                return ResourceManager.GetString("ZCoordinateDrainageConstruction_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z [m+NAP].
        /// </summary>
        public static string ZCoordinateDrainageConstruction_DisplayName {
            get {
                return ResourceManager.GetString("ZCoordinateDrainageConstruction_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Linker grens voor bepaling intredepunt van het glijvlak..
        /// </summary>
        public static string ZoneBoundaryLeft_Description {
            get {
                return ResourceManager.GetString("ZoneBoundaryLeft_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoneringsgrens links.
        /// </summary>
        public static string ZoneBoundaryLeft_DisplayName {
            get {
                return ResourceManager.GetString("ZoneBoundaryLeft_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rechter grens voor bepaling intredepunt van het glijvlak..
        /// </summary>
        public static string ZoneBoundaryRight_Description {
            get {
                return ResourceManager.GetString("ZoneBoundaryRight_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoneringsgrens rechts.
        /// </summary>
        public static string ZoneBoundaryRight_DisplayName {
            get {
                return ResourceManager.GetString("ZoneBoundaryRight_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zoneringsgrenzen automatisch bepalen of handmatig invoeren?.
        /// </summary>
        public static string ZoningBoundariesDeterminationType_Description {
            get {
                return ResourceManager.GetString("ZoningBoundariesDeterminationType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methode.
        /// </summary>
        public static string ZoningBoundariesDeterminationType_DisplayName {
            get {
                return ResourceManager.GetString("ZoningBoundariesDeterminationType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verticale coördinaat van de bovenkant van het rekengrid..
        /// </summary>
        public static string ZTop_Description {
            get {
                return ResourceManager.GetString("ZTop_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Z boven [m+NAP].
        /// </summary>
        public static string ZTop_DisplayName {
            get {
                return ResourceManager.GetString("ZTop_DisplayName", resourceCulture);
            }
        }
    }
}
