// Copyright (C) Stichting Deltares 2021. All rights reserved.
//
// This file is part of Riskeer.
//
// Riskeer is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with this program. If not, see <http://www.gnu.org/licenses/>.
//
// All names, logos, and references to "Deltares" are registered trademarks of
// Stichting Deltares and remain full property of Stichting Deltares at all times.
// All rights reserved.

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Plugins.Map.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Plugins.Map.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap AreaIcon {
            get {
                object obj = ResourceManager.GetObject("AreaIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Labels.
        /// </summary>
        internal static string Categories_Label {
            get {
                return ResourceManager.GetString("Categories_Label", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaartlaag.
        /// </summary>
        internal static string Categories_Layer {
            get {
                return ResourceManager.GetString("Categories_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaartlagenmap.
        /// </summary>
        internal static string Categories_MapDataCollection {
            get {
                return ResourceManager.GetString("Categories_MapDataCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stijl.
        /// </summary>
        internal static string Categories_Styling {
            get {
                return ResourceManager.GetString("Categories_Styling", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het criterium van deze categorie..
        /// </summary>
        internal static string CategoryThemeProperties_Criterion_Description {
            get {
                return ResourceManager.GetString("CategoryThemeProperties_Criterion_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Criterium.
        /// </summary>
        internal static string CategoryThemeProperties_Criterion_DisplayName {
            get {
                return ResourceManager.GetString("CategoryThemeProperties_Criterion_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} = {1}.
        /// </summary>
        internal static string CategoryThemeProperties_Criterion_ValueCriterionOperatorEqualValue_AttributeName_0_Value_1_ {
            get {
                return ResourceManager.GetString("CategoryThemeProperties_Criterion_ValueCriterionOperatorEqualValue_AttributeName_" +
                        "0_Value_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} ≠ {1}.
        /// </summary>
        internal static string CategoryThemeProperties_Criterion_ValueCriterionOperatorUnequalValue_AttributeName_0_Value_1_ {
            get {
                return ResourceManager.GetString("CategoryThemeProperties_Criterion_ValueCriterionOperatorUnequalValue_AttributeNam" +
                        "e_0_Value_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Toont de eigenschap op basis waarvan labels worden weergegeven op deze kaartlaag..
        /// </summary>
        internal static string FeatureBasedMapdata_SelectedMetaDataAttribute_Description {
            get {
                return ResourceManager.GetString("FeatureBasedMapdata_SelectedMetaDataAttribute_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Op basis van.
        /// </summary>
        internal static string FeatureBasedMapdata_SelectedMetaDataAttribute_DisplayName {
            get {
                return ResourceManager.GetString("FeatureBasedMapdata_SelectedMetaDataAttribute_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geeft aan of labels worden weergegeven op deze kaartlaag..
        /// </summary>
        internal static string FeatureBasedMapData_ShowLabels_Description {
            get {
                return ResourceManager.GetString("FeatureBasedMapData_ShowLabels_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weergeven.
        /// </summary>
        internal static string FeatureBasedMapData_ShowLabels_DisplayName {
            get {
                return ResourceManager.GetString("FeatureBasedMapData_ShowLabels_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het type van de stijl die wordt toegepast voor het weergeven van deze kaartlaag..
        /// </summary>
        internal static string FeatureBasedMapdata_StyleType_Description {
            get {
                return ResourceManager.GetString("FeatureBasedMapdata_StyleType_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string FeatureBasedMapdata_StyleType_DisplayName {
            get {
                return ResourceManager.GetString("FeatureBasedMapdata_StyleType_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het type van de data die wordt weergegeven op deze kaartlaag..
        /// </summary>
        internal static string FeatureBasedMapData_Type_Description {
            get {
                return ResourceManager.GetString("FeatureBasedMapData_Type_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        internal static string FeatureBasedMapData_Type_DisplayName {
            get {
                return ResourceManager.GetString("FeatureBasedMapData_Type_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijnen.
        /// </summary>
        internal static string FeatureBasedMapData_Type_Lines {
            get {
                return ResourceManager.GetString("FeatureBasedMapData_Type_Lines", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punten.
        /// </summary>
        internal static string FeatureBasedMapData_Type_Points {
            get {
                return ResourceManager.GetString("FeatureBasedMapData_Type_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygonen.
        /// </summary>
        internal static string FeatureBasedMapData_Type_Polygons {
            get {
                return ResourceManager.GetString("FeatureBasedMapData_Type_Polygons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kleur van de lijnen waarmee deze categorie wordt weergegeven..
        /// </summary>
        internal static string LineCategoryTheme_Color_Description {
            get {
                return ResourceManager.GetString("LineCategoryTheme_Color_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De stijl van de lijnen waarmee deze categorie wordt weergegeven..
        /// </summary>
        internal static string LineCategoryTheme_DashStyle_Description {
            get {
                return ResourceManager.GetString("LineCategoryTheme_DashStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De dikte van de lijnen waarmee deze categorie wordt weergegeven..
        /// </summary>
        internal static string LineCategoryTheme_Width_Description {
            get {
                return ResourceManager.GetString("LineCategoryTheme_Width_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap LineIcon {
            get {
                object obj = ResourceManager.GetObject("LineIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorieën.
        /// </summary>
        internal static string MapData_Categories_DisplayName {
            get {
                return ResourceManager.GetString("MapData_Categories_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kleur.
        /// </summary>
        internal static string MapData_Color_DisplayName {
            get {
                return ResourceManager.GetString("MapData_Color_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geeft aan of deze kaartlaag wordt weergegeven..
        /// </summary>
        internal static string MapData_IsVisible_Description {
            get {
                return ResourceManager.GetString("MapData_IsVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weergeven.
        /// </summary>
        internal static string MapData_IsVisible_DisplayName {
            get {
                return ResourceManager.GetString("MapData_IsVisible_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De naam van deze kaartlaag..
        /// </summary>
        internal static string MapData_Name_Description {
            get {
                return ResourceManager.GetString("MapData_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        internal static string MapData_Name_DisplayName {
            get {
                return ResourceManager.GetString("MapData_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijnkleur.
        /// </summary>
        internal static string MapData_StrokeColor_DisplayName {
            get {
                return ResourceManager.GetString("MapData_StrokeColor_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijndikte.
        /// </summary>
        internal static string MapData_StrokeThickness_DisplayName {
            get {
                return ResourceManager.GetString("MapData_StrokeThickness_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categorie.
        /// </summary>
        internal static string MapData_StyleType_Categories {
            get {
                return ResourceManager.GetString("MapData_StyleType_Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enkel symbool.
        /// </summary>
        internal static string MapData_StyleType_Single_Symbol {
            get {
                return ResourceManager.GetString("MapData_StyleType_Single_Symbol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geeft aan of deze kaartlagenmap wordt weergegeven..
        /// </summary>
        internal static string MapDataCollection_IsVisible_Description {
            get {
                return ResourceManager.GetString("MapDataCollection_IsVisible_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De naam van deze kaartlagenmap..
        /// </summary>
        internal static string MapDataCollection_Name_Description {
            get {
                return ResourceManager.GetString("MapDataCollection_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MapIcon {
            get {
                object obj = ResourceManager.GetObject("MapIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kleur van de lijnen waarmee deze kaartlaag wordt weergegeven..
        /// </summary>
        internal static string MapLineData_Color_Description {
            get {
                return ResourceManager.GetString("MapLineData_Color_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De stijl van de lijnen waarmee deze kaartlaag wordt weergegeven..
        /// </summary>
        internal static string MapLineData_DashStyle_Description {
            get {
                return ResourceManager.GetString("MapLineData_DashStyle_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijnstijl.
        /// </summary>
        internal static string MapLineData_DashStyle_DisplayName {
            get {
                return ResourceManager.GetString("MapLineData_DashStyle_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De dikte van de lijnen waarmee deze kaartlaag wordt weergegeven..
        /// </summary>
        internal static string MapLineData_Width_Description {
            get {
                return ResourceManager.GetString("MapLineData_Width_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shapebestand.
        /// </summary>
        internal static string MapPlugin_GetImportInfos_MapDataCollection_filefilter_Description {
            get {
                return ResourceManager.GetString("MapPlugin_GetImportInfos_MapDataCollection_filefilter_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to shp.
        /// </summary>
        internal static string MapPlugin_GetImportInfos_MapDataCollection_filefilter_Extension {
            get {
                return ResourceManager.GetString("MapPlugin_GetImportInfos_MapDataCollection_filefilter_Extension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MapPlusIcon {
            get {
                object obj = ResourceManager.GetObject("MapPlusIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kleur van de symbolen waarmee deze kaartlaag wordt weergegeven..
        /// </summary>
        internal static string MapPointData_Color_Description {
            get {
                return ResourceManager.GetString("MapPointData_Color_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De grootte van de symbolen waarmee deze kaartlaag wordt weergegeven..
        /// </summary>
        internal static string MapPointData_Size_Description {
            get {
                return ResourceManager.GetString("MapPointData_Size_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grootte.
        /// </summary>
        internal static string MapPointData_Size_DisplayName {
            get {
                return ResourceManager.GetString("MapPointData_Size_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kleur van de lijn van de symbolen waarmee deze kaartlaag wordt weergegeven..
        /// </summary>
        internal static string MapPointData_StrokeColor_Description {
            get {
                return ResourceManager.GetString("MapPointData_StrokeColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De dikte van de lijn van de symbolen waarmee deze kaartlaag wordt weergegeven..
        /// </summary>
        internal static string MapPointData_StrokeThickness_Description {
            get {
                return ResourceManager.GetString("MapPointData_StrokeThickness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het symbool waarmee deze kaartlaag wordt weergegeven..
        /// </summary>
        internal static string MapPointData_Symbol_Description {
            get {
                return ResourceManager.GetString("MapPointData_Symbol_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Symbool.
        /// </summary>
        internal static string MapPointData_Symbol_Displayname {
            get {
                return ResourceManager.GetString("MapPointData_Symbol_Displayname", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kleur van de vlakken waarmee deze kaartlaag wordt weergegeven..
        /// </summary>
        internal static string MapPolygonData_FillColor_Description {
            get {
                return ResourceManager.GetString("MapPolygonData_FillColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kleur van de lijn van de vlakken waarmee deze kaartlaag wordt weergegeven..
        /// </summary>
        internal static string MapPolygonData_StrokeColor_Description {
            get {
                return ResourceManager.GetString("MapPolygonData_StrokeColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De dikte van de lijn van de vlakken waarmee deze kaartlaag wordt weergegeven..
        /// </summary>
        internal static string MapPolygonData_StrokeThickness_Description {
            get {
                return ResourceManager.GetString("MapPolygonData_StrokeThickness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kaartlaag.
        /// </summary>
        internal static string Name_Layer {
            get {
                return ResourceManager.GetString("Name_Layer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kleur van de symbolen waarmee deze categorie wordt weergegeven..
        /// </summary>
        internal static string PointCategoryTheme_Color_Description {
            get {
                return ResourceManager.GetString("PointCategoryTheme_Color_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De grootte van de symbolen waarmee deze categorie wordt weergegeven..
        /// </summary>
        internal static string PointCategoryTheme_Size_Description {
            get {
                return ResourceManager.GetString("PointCategoryTheme_Size_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kleur van de lijn van de symbolen waarmee deze categorie wordt weergegeven..
        /// </summary>
        internal static string PointCategoryTheme_StrokeColor_Description {
            get {
                return ResourceManager.GetString("PointCategoryTheme_StrokeColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De dikte van de lijn van de symbolen waarmee deze categorie wordt weergegeven..
        /// </summary>
        internal static string PointCategoryTheme_StrokeThickness_Description {
            get {
                return ResourceManager.GetString("PointCategoryTheme_StrokeThickness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Het symbool waarmee deze categorie wordt weergegeven..
        /// </summary>
        internal static string PointCategoryTheme_Symbol_Description {
            get {
                return ResourceManager.GetString("PointCategoryTheme_Symbol_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap PointsIcon {
            get {
                object obj = ResourceManager.GetObject("PointsIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kleur van de vlakken waarmee deze categorie wordt weergegeven..
        /// </summary>
        internal static string PolygonCategoryTheme_FillColor_Description {
            get {
                return ResourceManager.GetString("PolygonCategoryTheme_FillColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De kleur van de lijn van de vlakken waarmee deze categorie wordt weergegeven..
        /// </summary>
        internal static string PolygonCategoryTheme_StrokeColor_Description {
            get {
                return ResourceManager.GetString("PolygonCategoryTheme_StrokeColor_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to De dikte van de lijn van de vlakken waarmee deze categorie wordt weergegeven..
        /// </summary>
        internal static string PolygonCategoryTheme_StrokeThickness_Description {
            get {
                return ResourceManager.GetString("PolygonCategoryTheme_StrokeThickness_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ZoomToAllIcon {
            get {
                object obj = ResourceManager.GetObject("ZoomToAllIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
