///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutomatedSystemTests.Modules.OpenViews
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The RotateMouseWheel recording.
    /// </summary>
    [TestModule("88e2392a-b0a8-4144-8df7-e88cb547c53f", ModuleType.Recording, 1)]
    public partial class RotateMouseWheel : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AutomatedSystemTests.AutomatedSystemTestsRepository repository.
        /// </summary>
        public static global::AutomatedSystemTests.AutomatedSystemTestsRepository repo = global::AutomatedSystemTests.AutomatedSystemTestsRepository.Instance;

        static RotateMouseWheel instance = new RotateMouseWheel();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public RotateMouseWheel()
        {
            deltaWheelMouseVertical = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static RotateMouseWheel Instance
        {
            get { return instance; }
        }

#region Variables

        string _deltaWheelMouseVertical;

        /// <summary>
        /// Gets or sets the value of variable deltaWheelMouseVertical.
        /// </summary>
        [TestVariable("a534115f-640e-48c6-83f3-cd9a0b1460f9")]
        public string deltaWheelMouseVertical
        {
            get { return _deltaWheelMouseVertical; }
            set { _deltaWheelMouseVertical = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse scroll Vertical by number of units from variable $deltaWheelMouseVertical.", new RecordItemIndex(0));
            Mouse.ScrollWheel(Int32.Parse(deltaWheelMouseVertical));
            Delay.Milliseconds(300);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
