//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ringtoets.Piping.Plugin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ringtoets.Piping.Plugin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kommagescheiden bestand.
        /// </summary>
        public static string Csv_file_name {
            get {
                return ResourceManager.GetString("Csv_file_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geïmporteerde data toevoegen aan faalmechanisme.
        /// </summary>
        public static string PipingSoilProfilesImporter_Adding_imported_data_to_model {
            get {
                return ResourceManager.GetString("PipingSoilProfilesImporter_Adding_imported_data_to_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 
        ///Het bestand wordt overgeslagen..
        /// </summary>
        public static string PipingSoilProfilesImporter_CriticalErrorMessage_0_File_Skipped {
            get {
                return ResourceManager.GetString("PipingSoilProfilesImporter_CriticalErrorMessage_0_File_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ondergrondschematiseringen importeren afgebroken. Geen data ingelezen..
        /// </summary>
        public static string PipingSoilProfilesImporter_Import_Import_cancelled {
            get {
                return ResourceManager.GetString("PipingSoilProfilesImporter_Import_Import_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlezen van de D-Soil Model database.
        /// </summary>
        public static string PipingSoilProfilesImporter_Reading_database {
            get {
                return ResourceManager.GetString("PipingSoilProfilesImporter_Reading_database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlezen van de ondergrondschematisering uit de D-Soil Model database.
        /// </summary>
        public static string PipingSoilProfilesImporter_ReadingSoilProfiles {
            get {
                return ResourceManager.GetString("PipingSoilProfilesImporter_ReadingSoilProfiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 
        ///Deze ondergrondschematisering wordt overgeslagen..
        /// </summary>
        public static string PipingSoilProfilesImporter_ReadSoilProfiles_ParseErrorMessage_0_SoilProfile_skipped {
            get {
                return ResourceManager.GetString("PipingSoilProfilesImporter_ReadSoilProfiles_ParseErrorMessage_0_SoilProfile_skipp" +
                        "ed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karakteristieke punten gevonden zonder bijbehorende profielmeting voor locatie &apos;{0}&apos;..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_AddImportedDataToModel_Characteristic_points_found_for_unknown_SurfaceLine_0_ {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_AddImportedDataToModel_Characteristic_points_found_" +
                        "for_unknown_SurfaceLine_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meerdere karakteristieke punten definities gevonden voor locatie &apos;{0}&apos;. Alleen de eerste definitie wordt geïmporteerd..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_AddImportedDataToModel_Duplicate_definitions_for_same_characteristic_point_location_0_ {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_AddImportedDataToModel_Duplicate_definitions_for_sa" +
                        "me_characteristic_point_location_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Meerdere definities gevonden voor profielmeting &apos;{0}&apos;. Alleen de eerste definitie wordt geïmporteerd..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_AddImportedDataToModel_Duplicate_definitions_for_same_location_0_ {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_AddImportedDataToModel_Duplicate_definitions_for_sa" +
                        "me_location_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er konden geen karakteristieke punten gevonden worden voor locatie &apos;{0}&apos;..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_AddImportedDataToModel_No_characteristic_points_for_SurfaceLine_0_ {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_AddImportedDataToModel_No_characteristic_points_for" +
                        "_SurfaceLine_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geïmporteerde data toevoegen aan faalmechanisme.
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_Adding_imported_data_to_model {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_Adding_imported_data_to_model", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Karakteristiek punt van profielmeting &apos;{0}&apos; is overgeslagen. {1}.
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_CharacteristicPoint_of_SurfaceLine_0_skipped_cause_1_ {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_CharacteristicPoint_of_SurfaceLine_0_skipped_cause_" +
                        "1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profielmeting {0} doorkruist de huidige referentielijn niet of op meer dan 1 punt en kan niet worden geïmporteerd..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_CheckReferenceLineInterSections_Surfaceline_0_does_not_correspond_to_current_referenceline {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_CheckReferenceLineInterSections_Surfaceline_0_does_" +
                        "not_correspond_to_current_referenceline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profielmeting {0} doorkruist de huidige referentielijn niet of op meer dan 1 punt en kan niet worden geïmporteerd. {1}.
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_CheckReferenceLineInterSections_Surfaceline_0_does_not_correspond_to_current_referenceline_1_ {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_CheckReferenceLineInterSections_Surfaceline_0_does_" +
                        "not_correspond_to_current_referenceline_1_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dit kan komen doordat de profielmeting een lokaal coordinaat systeem heeft..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_CheckReferenceLineInterSections_This_could_be_caused_coordinates_being_local_coordinate_system {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_CheckReferenceLineInterSections_This_could_be_cause" +
                        "d_coordinates_being_local_coordinate_system", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 
        ///Het bestand wordt overgeslagen..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_CriticalErrorMessage_0_File_Skipped {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_CriticalErrorMessage_0_File_Skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} Er zijn geen profielmetingen geïmporteerd..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_CriticalErrorMessage_0_No_sections_imported {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_CriticalErrorMessage_0_No_sections_imported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profielmetingen importeren afgebroken. Geen data ingelezen..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_Import_Import_cancelled {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_Import_Import_cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Geen karakteristieke punten-bestand gevonden naast het profielmetingenbestand. (Verwacht bestand: {0}).
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_Import_No_characteristic_points_file_for_surface_line_file_expecting_file_0_ {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_Import_No_characteristic_points_file_for_surface_li" +
                        "ne_file_expecting_file_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Er is geen referentielijn beschikbaar om profielmetingen voor te definiëren..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_Import_Required_referenceline_missing {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_Import_Required_referenceline_missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlezen &apos;{0}&apos;.
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_Read_PipingCharacteristicPoints_0_ {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_Read_PipingCharacteristicPoints_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlezen &apos;{0}&apos;.
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_Read_PipingSurfaceLines_0_ {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_Read_PipingSurfaceLines_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 
        ///Deze locatie met karakteristieke punten wordt overgeslagen..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_ReadCharacteristicPoints_ParseErrorMessage_0_CharacteristicPoints_skipped {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_ReadCharacteristicPoints_ParseErrorMessage_0_Charac" +
                        "teristicPoints_skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Begonnen met het inlezen van karakteristieke punten uit bestand &apos;{0}&apos;..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_ReadCharacteristicPoints_Start_reading_characteristic_points_from_file_0_ {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_ReadCharacteristicPoints_Start_reading_characterist" +
                        "ic_points_from_file_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlezen van het karakteristieke punten-bestand..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_Reading_characteristic_points_file {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_Reading_characteristic_points_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inlezen van het profielmetingenbestand..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_Reading_surface_line_file {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_Reading_surface_line_file", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} 
        ///Deze profielmeting wordt overgeslagen..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_ReadPipingSurfaceLines_ParseErrorMessage_0_SurfaceLine_skipped {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_ReadPipingSurfaceLines_ParseErrorMessage_0_SurfaceL" +
                        "ine_skipped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profielmeting {0} bevat aaneengesloten dubbele geometrie punten, welke zijn genegeerd..
        /// </summary>
        public static string PipingSurfaceLinesCsvImporter_SurfaceLine_0_has_multiple_duplicate_geometry_points_and_is_ignored {
            get {
                return ResourceManager.GetString("PipingSurfaceLinesCsvImporter_SurfaceLine_0_has_multiple_duplicate_geometry_point" +
                        "s_and_is_ignored", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DSoilModel bestand.
        /// </summary>
        public static string Soil_file_name {
            get {
                return ResourceManager.GetString("Soil_file_name", resourceCulture);
            }
        }
    }
}
