//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Plugins.CommonTools.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Plugins.CommonTools.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Algemeen.
        /// </summary>
        public static string Categories_General {
            get {
                return ResourceManager.GetString("Categories_General", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam.
        /// </summary>
        public static string Common_Name_DisplayName {
            get {
                return ResourceManager.GetString("Common_Name_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browser.
        /// </summary>
        public static string CommonToolsGuiPlugin_GetViewInfoObjects_Browser {
            get {
                return ResourceManager.GetString("CommonToolsGuiPlugin_GetViewInfoObjects_Browser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap HomeIcon {
            get {
                object obj = ResourceManager.GetObject("HomeIcon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korte beschrijving van het project..
        /// </summary>
        public static string ProjectProperties_Description_Description {
            get {
                return ResourceManager.GetString("ProjectProperties_Description_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Omschrijving.
        /// </summary>
        public static string ProjectProperties_Description_DisplayName {
            get {
                return ResourceManager.GetString("ProjectProperties_Description_DisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam van het getoonde project..
        /// </summary>
        public static string ProjectProperties_Name_Description {
            get {
                return ResourceManager.GetString("ProjectProperties_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Naam van de website of waar de URL naar verwijst gegevens..
        /// </summary>
        public static string UrlProperties_Name_Description {
            get {
                return ResourceManager.GetString("UrlProperties_Name_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Locatie waar de URL naar verwijst..
        /// </summary>
        public static string UrlProperties_Path_Description {
            get {
                return ResourceManager.GetString("UrlProperties_Path_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pad.
        /// </summary>
        public static string UrlProperties_Path_DisplayName {
            get {
                return ResourceManager.GetString("UrlProperties_Path_DisplayName", resourceCulture);
            }
        }
    }
}
