//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.17929
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Core.Components.Gis.IO.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Core.Components.Gis.IO.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestand bevat geen enkele lijn..
        /// </summary>
        internal static string LineShapeFileReader_File_contains_geometries_not_line {
            get {
                return ResourceManager.GetString("LineShapeFileReader_File_contains_geometries_not_line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestand bevat geen enkele punt..
        /// </summary>
        internal static string PointShapeFileReader_File_contains_geometries_not_points {
            get {
                return ResourceManager.GetString("PointShapeFileReader_File_contains_geometries_not_points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bestand bevat geen enkele polygoon..
        /// </summary>
        internal static string PointShapeFileReader_File_contains_geometries_not_polygons {
            get {
                return ResourceManager.GetString("PointShapeFileReader_File_contains_geometries_not_polygons", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Punten.
        /// </summary>
        internal static string PointShapeFileReader_ReadLine_Points {
            get {
                return ResourceManager.GetString("PointShapeFileReader_ReadLine_Points", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Een feature mag maar 1 geometrie bevatten..
        /// </summary>
        internal static string PointShapeFileWriter_CreatePointFromMapFeature_A_feature_can_only_contain_one_geometry {
            get {
                return ResourceManager.GetString("PointShapeFileWriter_CreatePointFromMapFeature_A_feature_can_only_contain_one_geo" +
                        "metry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Polygoon.
        /// </summary>
        internal static string PolygonShapeFileReader_ReadLine_Polygon {
            get {
                return ResourceManager.GetString("PolygonShapeFileReader_ReadLine_Polygon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lijn.
        /// </summary>
        internal static string PolylineShapeFileReader_ReadLine_Line {
            get {
                return ResourceManager.GetString("PolylineShapeFileReader_ReadLine_Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ingelezen element is een &apos;multi-lijn&apos;; alleen enkelvoudige lijn elementen worden ondersteund..
        /// </summary>
        internal static string PolylineShapeFileReader_ReadLine_Read_unsupported_multipolyline {
            get {
                return ResourceManager.GetString("PolylineShapeFileReader_ReadLine_Read_unsupported_multipolyline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to op index {0}.
        /// </summary>
        internal static string ShapeFileReaderBase_GetFeature_At_shapefile_index_0_ {
            get {
                return ResourceManager.GetString("ShapeFileReaderBase_GetFeature_At_shapefile_index_0_", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mapdata mag maar 1 feature bevatten..
        /// </summary>
        internal static string ShapeFileWriterBase_CopyToFeature_Mapdata_can_only_contain_one_feature {
            get {
                return ResourceManager.GetString("ShapeFileWriterBase_CopyToFeature_Mapdata_can_only_contain_one_feature", resourceCulture);
            }
        }
    }
}
