///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace AutomatedSystemTests.Modules.IO
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ComparePlainTextFiles recording.
    /// </summary>
    [TestModule("d35b3b3b-c87c-4fad-9f63-dcaf7835c8c8", ModuleType.Recording, 1)]
    public partial class ComparePlainTextFiles : ITestModule
    {
        /// <summary>
        /// Holds an instance of the global::AutomatedSystemTests.AutomatedSystemTestsRepository repository.
        /// </summary>
        public static global::AutomatedSystemTests.AutomatedSystemTestsRepository repo = global::AutomatedSystemTests.AutomatedSystemTestsRepository.Instance;

        static ComparePlainTextFiles instance = new ComparePlainTextFiles();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ComparePlainTextFiles()
        {
            filePath1 = "";
            filePath2 = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ComparePlainTextFiles Instance
        {
            get { return instance; }
        }

#region Variables

        string _filePath1;

        /// <summary>
        /// Gets or sets the value of variable filePath1.
        /// </summary>
        [TestVariable("2dfc00fd-73b9-4da3-8f6e-bb765817601f")]
        public string filePath1
        {
            get { return _filePath1; }
            set { _filePath1 = value; }
        }

        string _filePath2;

        /// <summary>
        /// Gets or sets the value of variable filePath2.
        /// </summary>
        [TestVariable("4b82dd79-7c11-425a-9f41-b9795be8d16b")]
        public string filePath2
        {
            get { return _filePath2; }
            set { _filePath2 = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Ranorex.AutomationHelpers.UserCodeCollections.FileLibrary.ValidateFilesTextEqual(filePath1, filePath2);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
