///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// Your custom recording code should go in this file.
// The designer will only add methods to this file, so your custom code won't be overwritten.
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.IO;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomatedSystemTests.Modules.IO
{
    public partial class CreateOutputFolder
    {
        /// <summary>
        /// This method gets called right after the recording has been started.
        /// It can be used to execute recording specific initialization code.
        /// </summary>
        private void Init()
        {
            // Your recording specific initialization code goes here.
        }

        public string CreateFolderForOutput(string caseNumber)
        {
            string rootOutputFolder = Directory.GetCurrentDirectory() + @"\output";
            CreateFolderIfItDoesNotExist(rootOutputFolder);
            string path = Directory.GetCurrentDirectory() + @"\script" + caseNumber;
            CreateFolderIfItDoesNotExist(path);
            return rootOutputFolder;
        }
        
        private void CreateFolderIfItDoesNotExist(string pathFolder)
        {
            try
            {
                // Determine whether the folder exists.
                if (Directory.Exists(pathFolder))
                {
                    Report.Log(ReportLevel.Info, "Path " + pathFolder + " already exists.");
                    return;
                }
                // Try to create the folder.
                DirectoryInfo di = Directory.CreateDirectory(pathFolder);
                Report.Log(ReportLevel.Info, "The folder " + pathFolder + " was created successfully at " + Directory.GetCreationTime(pathFolder) + ".");
            }
            catch (Exception e)
            {
                Report.Log(ReportLevel.Error, "Creating the folder " + pathFolder + " failed: {0}", e.ToString());
            }
            finally {}
        }

    }
}
